### ISSUE TITLE
PublishPress Future PRO Translation Updates v.4.0.3

### ISSUE THREAD

**Issue by wocmultimedia** [publishpress/PublishPress-Future#1000]
Hi @andergmartins , @stevejburge ,

Here's copy of PublishPress Future PRO Translation Updates v.4.0.3.
[TranslationUpdates_PublishpressFuture-PRO-4.0.3.zip](https://github.com/user-attachments/files/17504243/TranslationUpdates_PublishpressFuture-PRO-4.0.3.zip)

**Comment by andergmartins** [comment]
Thanks @wocmultimedia!
