### ISSUE TITLE
Move the Scheduled Actions to a button

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Future#1022]
Add a button up to the title of Action Workflows, for "Scheduled Actions", and remove it from the main menu. Action Workflows become the first menu item.

![image](https://github.com/user-attachments/assets/ad92d825-9b78-4856-ac4a-aa204f400959)

That screen is become busier, so let's remove it from the main area.

**Comment by stevejburge** [comment]
Should we put this button on "Action Settings" too? It applies equally to that area
