### ISSUE TITLE
PublishPress Future Free & PRO Translation Updates v.4.1.0

### ISSUE THREAD

**Issue by wocmultimedia** [publishpress/PublishPress-Future#1026]
@andergmartins, @stevejburge 
Hi,  
1-I updated the files of Future Free on WP.org
2-Inside the Future PRO I found the same mingled  ES-FR-IT files again  that might cause a block because are corrupted.
These problem is only for the mentioned languages because others like Brazilian has to be updated but is correct.

**Comment by andergmartins** [comment]
Thanks @wocmultimedia.
Regarding improving our process, would you prefer we update only the `.pot` file and leave the `.po` files untouched for you?
I was running a script to update it based on recent changes in the `.pot` file.

**Comment by wocmultimedia** [comment]
Hi @andergmartins ,
Yes. You just update the .pot file to latest plugin version and I do the rest because sometimes you haven't added my previous files and the new files can results mingles or with more strings to changes than needed. I am used to checking previous version before making new updates and translation.
So, again, Yes! Don only file .pot update.
Thanks

**Comment by andergmartins** [comment]
Sounds like a plan, thanks

**Comment by wocmultimedia** [comment]
It's the fastest and simplest way for both, you and me. Having the .pot updated I just need to open PoEdit and make Update from file pot to have the .po file updated for new translation.
