### ISSUE TITLE
"Action Workflow Editor" -replace title to this not only for PublishPress pages

### ISSUE THREAD

**Issue by RichardFerlow** [publishpress/PublishPress-Future#1037]
ver 4.1.1   
This function replace Title in many admin pages - woocommerce settings, different plugins, etc
Wordpress 6.7 Woocommerce 9.4.1

```
 public function fixWorkflowEditorPageTitle()
    {
        global $title;

        $title = __("Action Workflow Editor", "post-expirator");
    }
```

**Comment by rizaardiyanto1412** [comment]
Thanks for reporting this @RichardFerlow 

I could confirm this.

I will let our dev know about it

**Comment by andergmartins** [comment]
Thank you, @RichardFerlow. There was an additional lost commit during the code merge for the release. We will address and resolve it.
