### ISSUE TITLE
Center the Pro button

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#1049]
![Screenshot 2024-11-21 at 2 58 31 PM](https://github.com/user-attachments/assets/aa9a8d7d-864b-47a5-897d-b19c956e63cc)

**Comment by andergmartins** [comment]
I think this is already solved. 
![image](https://github.com/user-attachments/assets/51e9b18c-e9a7-4b6b-a584-cb71c61077c8)


![image](https://github.com/user-attachments/assets/5e8cc330-d27c-4752-b6a0-c8b3b288acc3)
