### ISSUE TITLE
Small display issue with Future metabox

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#1056]
![Screenshot 2024-11-22 at 2 19 40 PM](https://github.com/user-attachments/assets/f80cd582-fcc3-4d01-8153-12e754179029)

**Comment by stevejburge** [comment]
Quick Edit also:
![Screenshot 2024-11-22 at 2 36 02 PM](https://github.com/user-attachments/assets/931430c0-dcd0-4b47-a904-91c86a5eb141)

**Comment by andergmartins** [comment]
Fixed on #1057
