### ISSUE TITLE
Add new trigger: metadata changes

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#1059]
Can we add a trigger to allow workflows to start if metadata changes on a post.

We've had at least a couple of requests along these lines:

- Send an alert when specific metadata changes on a post (example, the publish date)
- Send an alert when the permalink changes

**Comment by andergmartins** [comment]
@stevejburge to clarify, the new trigger only watches changes on the metadata table, not the publish date. For this, we should use the Post Updated trigger and a conditional step with a condition verifying the new and old publish dates, like the following:

![image](https://github.com/user-attachments/assets/238b44ac-a37e-4c65-8664-08d0b603da99)

The same will be true for the permalink changes:

![image](https://github.com/user-attachments/assets/0474a36f-b15e-48c2-8bed-45f4ecf20459)

**Comment by stevejburge** [comment]
Thanks @andergmartins
