### ISSUE TITLE
Saving a workflow is very slow

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#1064]
When I'm creating new workflows, the Save button seems very slow. I end up clicking it multiple times and getting this:
![Screenshot 2024-12-04 at 4 55 49 PM](https://github.com/user-attachments/assets/a71d0f49-6b3e-4484-b9ab-ab04bb52b224)

**Comment by andergmartins** [comment]
We are disabling screenshots to reduce the resources usage, #1066
