### ISSUE TITLE
Deactivation of the plugin does not remove the cron jobs and settings

### ISSUE THREAD

**Issue by contactashish13** [publishpress/PublishPress-Future#107]
## Expected Behavior

Deactivation of the plugin should clear the cron jobs for the plugin

## Current Behavior

Deactivation of the plugin does not clear the cron jobs for the plugin

## Steps to Reproduce (for bugs)

1. Activate the plugin
2. Enable expiry for a post
3. Check the cron job has been added
4. Deactivate the plugin
5. The cron job will remain

**Comment by andergmartins** [comment]
The cron jobs should be removed from WP cron (for legacy expiration actions) and from the new action scheduler table implemented on #149.
