### ISSUE TITLE
PublishPress Future Free ES-FR-IT Translation Updates v.4.2.0

### ISSUE THREAD

**Issue by wocmultimedia** [publishpress/PublishPress-Future#1077]
@andergmartins, @stevejburge
Hi,
1-I updated the files of Future Free v.4.2.0 on WP.org
2-I also updated the 3 different types of .po files related to ES-FR-IT translations inside the plugin languages folder. 
Please, take note that the .json and .php files are not included and you should create them.

Here's copy of the files
[ES-FR-IT_TranslationUpdates_Future-4.2.0.zip](https://github.com/user-attachments/files/18082024/ES-FR-IT_TranslationUpdates_Future-4.2.0.zip)

**Comment by andergmartins** [comment]
Thanks!
