### ISSUE TITLE
Explanation for post meta changed

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#1080]
We'll need details on how to use this. Maybe a documentation link?
![Screenshot 2024-12-13 at 5 21 24 PM](https://github.com/user-attachments/assets/b17771f9-0823-4b4f-90c5-f58c31f2c7bf)

**Comment by andergmartins** [comment]
@stevejburge a documentation link sounds great. Maybe we could add that for all the available steps using a "Learn more" link?

![image](https://github.com/user-attachments/assets/dbcbdc6d-1427-4d90-bfc1-619219dd4a43)

If so, what would be a good text for that?

* Learn more
* How this works

**Comment by stevejburge** [comment]
Yes, please.

"This field allow you to choose the post meta that will trigger this action. Learn more."
