### ISSUE TITLE
Post status changed is unclear

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#1081]
I'm not quite sure how to use this option. We'll need to add some details
![Screenshot 2024-12-13 at 5 24 16 PM](https://github.com/user-attachments/assets/df62ecc2-774a-4ec5-b3ee-4f8ade227899)

For example, will this be triggered when posts move to these new statuses?

![Screenshot 2024-12-13 at 5 25 17 PM](https://github.com/user-attachments/assets/c1abcad4-dbcc-40f0-8aef-8d681a4ee6d7)

**Comment by andergmartins** [comment]
@stevejburge yes, and I've added field descriptions to make that clearer.
![image](https://github.com/user-attachments/assets/f3c6455a-81b1-41f0-a688-529611d8dc38)

**Comment by stevejburge** [comment]
Thanks @andergmartins. Still not 100% clear. Are these the statuses before the change, or after the change?
