### ISSUE TITLE
All post now carry the default expiration

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#115]
I can confirm this bug report:
https://wordpress.org/support/topic/all-post-now-carry-default-expiration-even-when-not-selected/

Enter a default time in Post Types:
<img width="824" alt="Screen Shot 2021-09-14 at 3 18 00 PM" src="https://user-images.githubusercontent.com/3868028/133320295-91292f7a-3d1e-4a3f-b8c3-c1bd2a0ece51.png">

That will now be the active default for all posts, even if Post Expirator is not enabled

**Comment by contactashish13** [comment]
@stevejburge Here are the steps I followed to reproduce this. Please let me know if there are other scenarios/steps to replicate this issue.

1. clear the settings
2. go the Post Types and choose a custom expiration date
3. Edit a post that does not have an expiry set and without checking the Post Expirator box, save it
4. In the post listing the post **shows an expiration date** corresponding to the custom expiration date
5. go to settings and choose Classic Editor style box
6. go to another post that does not have an expiry set and without checking the Post Expirator box, save it
7. In the post listing screen, the post **shows no expiration date**

PR https://github.com/publishpress/PublishPress-Future/pull/118 should fix this. Till this fix is released, users can avoid this problem by choosing this option instead

![image](https://user-images.githubusercontent.com/12953439/133369093-191f3d4c-2d59-4bfb-8ca1-c419cd57f220.png)
