### ISSUE TITLE
Set a default time

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#12]
> An addition I would be grateful for is: Setting a default time per posts (in the defaults)

https://wordpress.org/support/topic/love-it-3480/

**Comment by contactashish13** [comment]
@stevejburge just to make sure I understand this correctly, does this mean a section like this for every post type?

![image](https://user-images.githubusercontent.com/12953439/125562947-88d8456b-4ae5-4188-b5b1-b9db46429699.png)

**Comment by stevejburge** [comment]
@contactashish13 yes, please

**Comment by contactashish13** [comment]
@stevejburge Sorry, I merged the PR thinking it was part of 2.5 and then found it was part of 2.7. I guess we will have to move this to 2.5 now

**Comment by stevejburge** [comment]
@contactashish13 This seems to work great in the post editor. I set this to "+1 month" and it's August 18 today:
![Screen Shot 2021-08-18 at 9 44 59 AM](https://user-images.githubusercontent.com/3868028/129909170-7a8bb9dd-6e98-40e9-8a47-85e6c85cdb52.png)

However, no luck with Quick Edit:
![Screen Shot 2021-08-18 at 9 45 22 AM](https://user-images.githubusercontent.com/3868028/129909302-3a5fbcbc-8bca-46c1-9988-a1e423d1f2b6.png)
