### ISSUE TITLE
Category replace not working with new Gutenberg box

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#127]
> "category replace" does not work when the "Gutenberg style box" is selected in the settings. When the "Classic style box" is selected the "category replace" works fine.

https://wordpress.org/support/topic/gutenberg-style-box-does-not-seem-to-work/

**Comment by contactashish13** [comment]
@stevejburge this looks like a duplicate of #128.

**Comment by stevejburge** [comment]
One more report https://wordpress.org/support/topic/posts-expiring-at-random-times/#post-14918385

> It seems to happen only when posts are set to expire to a category, not a change in post status.
