### ISSUE TITLE
More Gutenberg and category issues

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#128]
> If the "Gutenberg style box" is selected: when I make a new post and I select select "category replace" and choose the replace-category, this category is not being saved when I publish the post. When I select the replace-category again and update the post, only than the replace-category is saved.

**Comment by contactashish13** [comment]
@stevejburge I cannot replicate this. Maybe this is similar to #82?

**Comment by andergmartins** [comment]
@stevejburge I can't replicate this too. Please, could you double-check?
