### ISSUE TITLE
When post expires to draft, the post creates a new cron job

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#130]
> What I'm seeing when the post expires and is set to draft, it appears to create another cron job for the draft post set to run at the exact time the post was supposed to expire when published.  It then seems that the job is stuck in the cron queue since the job's set time is already past.

https://wordpress.org/support/topic/when-post-expires-to-draft-recreates-cron-job/

**Comment by contactashish13** [comment]
@stevejburge I cannot replicate this behavior. The post becomes a draft and the cron job disappears.
