### ISSUE TITLE
Wrong time showing - only UTC

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#134]
I can confirm this report:
https://wordpress.org/support/topic/2-5-0-crashed-custom-settings-gutenberg-style-doesnt-work-properly/#post-14906785

> This currently displays GMT time with AM + PM (12 hour format) & not our time zone (Europe = currently GMT+2, soon GMT+1, 24 hour format). The classic style works like charm.

Here's my site:
<img width="485" alt="Screen Shot 2021-09-24 at 2 41 18 PM" src="https://user-images.githubusercontent.com/3868028/134724844-a0ee4909-9397-479d-98e6-cbb0d9f3a51c.png">

The site is setup to be 4 hours behind the time showing in the editor:
<img width="572" alt="Screen Shot 2021-09-24 at 2 43 24 PM" src="https://user-images.githubusercontent.com/3868028/134724911-a40c6289-af51-4c00-bc0b-8923c29a5fff.png">

**Comment by stevejburge** [comment]
One more here with screenshots: https://wordpress.org/support/topic/i-get-different-dates-one-in-the-editor-and-the-other-in-all-alerts-view/

**Comment by andergmartins** [comment]
One more: https://secure.helpscout.net/conversation/1676879034/153567?folderId=2557470 (private link)

**Comment by stevejburge** [comment]
A couple more on the WordPress forums:
https://wordpress.org/support/topic/exipiration-time-does-not-recognize-site-settings/
https://wordpress.org/support/topic/php-warning-318/
