### ISSUE TITLE
Gutenberg version of expiration block is not working

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#136]
I can confirm this report:
https://wordpress.org/support/topic/set-expirator-at-block-editor-will-not-expired/

Set the expiry time here:
<img width="323" alt="Screen Shot 2021-09-24 at 3 08 09 PM" src="https://user-images.githubusercontent.com/3868028/134727685-14bdc994-d714-48c9-a08f-4e2c91ce1530.png">

The post shows that the expiry is set:
<img width="1012" alt="Screen Shot 2021-09-24 at 3 04 05 PM" src="https://user-images.githubusercontent.com/3868028/134727456-97c8f6fa-41da-4c7a-8c1c-be860f382074.png">

But nothing in the debug log or in the site's cron schedules
<img width="935" alt="Screen Shot 2021-09-24 at 3 04 11 PM" src="https://user-images.githubusercontent.com/3868028/134727615-b5c033b9-183a-43e9-ac04-591ee533f10d.png">

**Comment by andergmartins** [comment]
>It seems to work if I do Quick edit first, then update in the post (edited) 
>The post is not creating new cron jobs
