### ISSUE TITLE
Warning: Trying to access array offset on value of type bool in views/quick-edit.php

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Future#140]
When opening the quick edit panel for a post, I see the following warning:

>Warning: Trying to access array offset on value of type bool in /Users/anderson/Local Sites/dev/app/public/wp-content/plugins/post-expirator/views/quick-edit.php on line 51

![image](https://user-images.githubusercontent.com/407131/134985652-0568883d-8211-4903-8535-87191c370e14.png)

### Context

PHP 8.0

**Comment by stevejburge** [comment]
@andergmartins Ouch, we tried to fix that one in 2.5.1

**Comment by andergmartins** [comment]
Closing this one. I can't replicate it anymore on PHP 8.
