### ISSUE TITLE
hierarchical taxonomy – Selection error in the settings

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#144]
https://wordpress.org/support/topic/hierarchical-taxonomy-selection-error/#post-14917279

> I’m getting errors as follows in the classic editor (custom post type)

```
Expiration Categories:
More than 1 heirachical taxonomy detected. You must assign a default taxonomy on the settings screen.

```

**Comment by stevejburge** [comment]
> 
> 
> I had similar issue with default Category and find out ‘_expiration-date-taxonomy’ meta field was empty in ‘postmeta’ table.
> 
> When in
> post-expirator/classes/Facade.class.php
> line 249
> $taxonomyName = isset( $opts[‘categoryTaxonomy’] ) ? $opts[‘categoryTaxonomy’] : ”;
> I replace with
> $taxonomyName = isset( $opts[‘categoryTaxonomy’] ) ? $opts[‘categoryTaxonomy’] : ‘category’;
> to set default taxonomy it works well.

https://wordpress.org/support/topic/category-replace-add-remove-not-working-with-custom-post-types/

**Comment by bobuehlein** [comment]
Having this same issue on 2.7.3. Multisite install where some of the sites work as they should, and others are showing the categories. I updated the facade.class.php file as mentioned here but that didn't seem to help. 

I am using the classic editor plugin (on all of the sites in this network) There is nothing in my apache error logs about this. 

The _expiration-date-taxonomy meta value is blank in the postmeta table for this site. 

I'm about to go line by line in our theme to see what the differences could be... but I am unable to find a common point on sites that are failing to use the plugin.

**Comment by stevejburge** [comment]
Re-opening this because of another report.

**Comment by dj-jetta** [comment]
Having the same Problem. If you select a category in settings and hit save it doesn't keep the selected category. 

Multisite
Greyd-Suite Theme with Global Content
WPML

**Comment by stevejburge** [comment]
Related: https://wordpress.org/support/topic/compatibility-issues-post-types-from-divi-engine/

**Comment by stevejburge** [comment]
https://wordpress.org/support/topic/after-update-dont-work-category-replace/#post-15289631

> 
> the issue is back. In new version our plugin I see the same error: “More than 1 heirachical taxonomy detected. You must assign a default taxonomy on the settings screen.”
> In settings tab “post types” I see taxonomies but when I select it and click save – changes are not saved in the database.
> 
> In 2.7.0 version is ok.
