### ISSUE TITLE
Serious saving error in Gutenberg editor

### ISSUE THREAD

**Issue by mbernth** [publishpress/PublishPress-Future#152]
After updating to 2.6.0 my website started to experience serious errors to the Gutenberg editor. Post title, parts of content text and featured image didn’t get get saved in draft or when published. The editor came with a warning that it had encountered an unexpected error and the error log showed a number of JS errors. 

![5c794b4c63a1b00fa9c9d400c78551ac93cf2bac](https://user-images.githubusercontent.com/1203042/136416189-995704fc-d4c2-433e-8150-324ee8ffc15e.png)
![47186cd921f5fc27fb2388c4e65ecefa122c055c](https://user-images.githubusercontent.com/1203042/136416192-4efba0d3-a60e-4ee8-a16f-b6e3e3214736.png)

When I disabled Post Expirator, WordPress ran smoothly and error-free again.

The website is running on WP 5.8.1, PHP 7.4 on a Genesis platform. Post Expirator is inactive for everything except a custom post type. Version 2.5.0 has previously been working without errors.

**Comment by andergmartins** [comment]
We are closing this for now, but feel free to comment again here in case you still need help, so we reopen the ticket.
