### ISSUE TITLE
Add visual indicators that the cron task is created correctly

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#155]
I wonder if we can add a visual indicator confirming that the cron task was created/updated correctly?

At the moment, you save the date and have no idea if it has worked.

It would be great if it was 100% clear that the task was created.

There could be a green checkmark here? Maybe with a link to the "Diagonostics" tab:
<img width="326" alt="Screen Shot 2021-10-11 at 2 16 50 PM" src="https://user-images.githubusercontent.com/3868028/136836122-b00cc7af-8fca-44ce-8e74-a3533b0c3963.png">

Any maybe the same here:
<img width="575" alt="Screen Shot 2021-10-11 at 2 17 50 PM" src="https://user-images.githubusercontent.com/3868028/136836165-5ace8c30-18e8-47f6-9a82-615dc05d5211.png">

We could add details of the related post here:
<img width="1206" alt="Screen Shot 2021-10-11 at 2 18 51 PM" src="https://user-images.githubusercontent.com/3868028/136836282-7d36a2d2-33d8-4306-8d3c-8186b17130f3.png">

**Comment by andergmartins** [comment]
@stevejburge maybe we could add the visual indicator in the Expires column, instead?

![image](https://user-images.githubusercontent.com/407131/144475589-ff56cbb5-2891-4f80-912e-6852a957c21e.png)

**Comment by stevejburge** [comment]
@andergmartins Yes, that's a better idea than mine

**Comment by andergmartins** [comment]
Sounds good, so I will keep the solution I've implemented. Thanks
