### ISSUE TITLE
Add remove category not available in pages post type 

### ISSUE THREAD

**Issue by ludoviclenoir** [publishpress/PublishPress-Future#157]
<img width="288" alt="Capture d’écran 2021-10-15 à 14 58 35" src="https://user-images.githubusercontent.com/25514491/137491034-39b2276e-b21a-4773-8ce4-039e78623d6b.png">

**Comment by stevejburge** [comment]
Related issue here, with non-standard taxonomies: https://github.com/publishpress/PublishPress-Future/issues/50
