### ISSUE TITLE
Auto Enable Default settings not working

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#158]
https://wordpress.org/support/topic/auto-enable-not-working/
I can confirm this report. Again, it seems to be a Gutenberg issue. This works correctly with Quick Edit and Classic Editor

The settings show correctly:
<img width="306" alt="Screen Shot 2021-10-15 at 10 55 11 AM" src="https://user-images.githubusercontent.com/3868028/137508173-1e7c2634-6ddb-439e-ac40-e27ca9757ae7.png">

However, the save the post and this appears: "Never". And there's no cron job
<img width="1191" alt="Screen Shot 2021-10-15 at 10 53 57 AM" src="https://user-images.githubusercontent.com/3868028/137508223-3a0ee701-2435-4ac6-bbbb-2593462b3897.png">

**Comment by stevejburge** [comment]
Another report here: https://wordpress.org/support/topic/post-expirator-not-recognizing-change-when-updating/

**Comment by timjh** [comment]
My experience with the problem is entirely in the Classic Editor. The site does not use Gutenberg at all.

**Comment by timjh** [comment]
Thanks for getting back to me. I still have the same problem with both the current live version of Post Expirator (2.6.1) and the 2.6.1-beta3 version: the plugin seems to treat any update as it would a new post, and insists on re-enabling expiration if, in settings, I have  Auto-Enable set for the post type. My workaround is to have Auto-Enable disabled; I then have complete control when editing.

 

--

Tim Huckvale

**Comment by andergmartins** [comment]
@timjh please, could you double-check if that is a cache problem? Please, could you try again cleaning up the browser cache?

**Comment by timjh** [comment]
I have no WordPress caching plugin, and clearing the browser cache (Firefox and Edge) makes no difference.

 

--

Tim Huckvale
