### ISSUE TITLE
Category-based expiration not working for custom post types in classic editor

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#169]
Details here: https://wordpress.org/support/topic/category-based-expiration-not-working-for-custom-post-types-in-classic-editor/

> In the /post-expirator/views/classic-metabox.php file, add a new, uniquely-named variable on its own line immediately below line 133:
> 
> `$uniquely_prefixed_defaults = get_option( 'expirationdateDefaults' . ucfirst( $post->post_type ) );`
> 
> Then, on lines 140 and 147, replace all instances of $defaults[‘taxonomy’] with $uniquely_prefixed_defaults[‘taxonomy’]

**Comment by andergmartins** [comment]
Duplicates #144. Fixed on the other issue.
