### ISSUE TITLE
Uncaught Error: Undefined constant "expireType"

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#173]
An error report with the Gutenberg box:

`Uncaught Error: Undefined constant "expireType" in plugins\post-expirator\post-expirator.php:617`

https://wordpress.org/support/topic/after-update-error-when-editing-with-elementor/#post-15026532

**Comment by stevejburge** [comment]
@andergmartins I think this a typo? https://wordpress.org/support/topic/after-update-error-when-editing-with-elementor/#post-15027927

> There is a typo on line 617 and 619. In both places $opts[expireType] should be $opts['expireType']
> 
> add those quotes to fix it.

**Comment by andergmartins** [comment]
@stevejburge yes, thanks. That was the fix. I committed it yesterday for the issue #172. Closing this one as duplicated.
