### ISSUE TITLE
Invalid access to array by using a non-constant keyword like a string

### ISSUE THREAD

**Issue by yskkuwahara** [publishpress/PublishPress-Future#176]
Hi, my wordpress site uses Post Expirator(version 2.6.1) plugin.
Today I have posted with an auto expiration, then I got the warning message like below.

```
Warning: Use of undefined constant expireType - assumed 'expireType' (this will throw an Error in a future version of PHP)
```

```php
/wp-content/plugins/post-expirator/post-expirator.php in postexpirator_update_post_meta at line 617

            } else {
                $ts = get_post_meta($id, '_expiration-date', true);
            }
            if (isset($payload['meta']['_expiration-date-type'])) {
                $opts[expireType] = $payload['meta']['_expiration-date-type'];
            } else {
                $opts[expireType] = get_post_meta($id, '_expiration-date-type', true);
            }
            if (isset($payload['meta']['_expiration-date-categories'])) {
```

https://github.com/publishpress/PublishPress-Future/blob/main/post-expirator.php#L617-L619

It seems to be occurred at `$opts[expireType]`.

I hope your corresponding.
Sincerely yours.

## Expected Behavior
No warning occurs by posting with setting an expiration.

## Current Behavior
Warning occurs.

## Possible Solution
Set quotes to a keyword by sides like below.

`$opts[expireType]` -> `$opts['expireType']`

**Comment by stevejburge** [comment]
Thanks for such a helpful bug report @yskkuwahara 

I think we have a fix for this in 2.6.2 which is about to release, but I'll check with our team

**Comment by andergmartins** [comment]
I can confirm the fix, but thanks for reporting that. We are about to release the new version.

**Comment by yskkuwahara** [comment]
It's nice to hear that! Thanks for fixing it and release new one quickly.
