### ISSUE TITLE
Category Replace and Quick Edit

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#179]
> However, when using Category Replace, only the new categories are shown when editing the post (which I take to be correct), but the Quick Edit shows the current categories as well as the new ones (which is misleading). If I delete the current categories in Quick Edit and update, then Quick Edit again, the current categories are still shown.
> 
> It appears that it works correctly and the current categories are removed and replaced as expected at the expiry time. It seems that just the display in Quick Edit is wrong.

https://wordpress.org/support/topic/category-replace-in-quick-edit-shows-current-categories/

Can confirm ... in this example, "Uncategorized" shouldn't be checked

<img width="374" alt="Screen Shot 2021-11-08 at 4 42 11 PM" src="https://user-images.githubusercontent.com/3868028/140822914-11d9bd15-27fe-43cf-8e14-16be1e2af1e6.png">

<img width="580" alt="Screen Shot 2021-11-08 at 4 43 34 PM" src="https://user-images.githubusercontent.com/3868028/140822947-b97dc03d-5bdb-48bb-979a-58533f06907d.png">

**Comment by andergmartins** [comment]
Fixed on b19b2bebd265c2bfc0f30a3f68a62065284a8c51
