### ISSUE TITLE
PE seems to be setting an unwanted expiry time

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#187]
https://wordpress.org/support/topic/posts-expire-when-i-try-to-edit/#post-15086182

> Posts expire when I try to edit.
> 
> The problem happens before I even hit save. I open an post to edit it, and the Post Expirator is activated with a random date and time. I checked the log. Here's a sample of what it says:
> 
> 2021-11-18 21:02:29 9725 -> NO PAYLOAD ON SAVE_POST
> 2021-11-18 21:02:25 9725 -> SCHEDULED at Thu, 18 Nov 2021 22:02:25 -0500 () with options Array ( [expireType] => [category] => Array ( [0] => ) [id] => 9725 ) Event timestamp must be a valid Unix timestamp.
> 
> For what it's worth, it's happening on a different website I manage - different host, different WP template. Half the website was in draft mode after I updated several pages.

2 more reports here: https://wordpress.org/support/topic/pages-expiring-despite-settings-off/#post-15086826

One use seems to have resolved this with Bulk Edit:

> I've resolved this issue by the following:
> 
> 1. WP Dashboard - Pages - All Pages
> 2. Select all (because I don't want any pages to expire)
> 3. Bulk Actions - Edit
> 4. Post Expirator - Remove

**Comment by stevejburge** [comment]
@andergmartins One more https://wordpress.org/support/topic/expirator-automatically-expiring-posts-in-version-2-6-3/#post-15100938

**Comment by andergmartins** [comment]
We received positive feedback saying that is fixed.
