### ISSUE TITLE
Add back support for Reusable Blocks

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#200]
> I work on a site with v2.3.0 of this plugin installed, which allows us to set expiry on reusable Gutenberg blocks. Recently updating the plugin to v2.7.0 has removed this feature. Nothing in the settings appears to re-enable the feature. Is this intended behaviour or a bug?
> 
> Either way, I would like to request that it be added back in.

https://wordpress.org/support/topic/reusable-blocks-10/

**Comment by andergmartins** [comment]
I was not able to find this feature working on v2.3.0 as reported by the user. But we can take a look on this again after, or when implementing the issue https://github.com/publishpress/PublishPress-Blocks/issues/1066.

**Comment by andergmartins** [comment]
We removed access to this when we excluded bulti-in post types from the plugin.

I was testing and it is possible now to reactivate it for Patterns (reusable blocks). The expiration date can be set following the steps:

![Screenshot 2024-01-12 at 18 07 05](https://github.com/publishpress/PublishPress-Future/assets/407131/0724848d-73f6-47b0-af07-10ab48777a78)

![Screenshot 2024-01-12 at 18 06 31](https://github.com/publishpress/PublishPress-Future/assets/407131/f90487dd-9188-4767-a1a9-4cd5497f75fc)

![Screenshot 2024-01-12 at 18 06 10](https://github.com/publishpress/PublishPress-Future/assets/407131/f2b92316-99f8-4e19-8218-d9678af340b7)
