### ISSUE TITLE
Double email sending

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#204]
https://wordpress.org/support/topic/double-email-notifications-4/

> We have set ‘Enable Email Notifications?’ to Enabled and ‘Include Blog Administrators’ as Disabled.
> 
> All ‘message expired’ notifications arrive double on the address specified in the field ‘Who to notify:’
> 
> I compared the Email headers of the 2 messages. All fields are exactly the same except for ‘Message ID:’

I can confirm this:

<img width="1318" alt="Screen Shot 2022-01-04 at 6 45 58 PM" src="https://user-images.githubusercontent.com/3868028/148139012-8eb8cf31-44a5-418e-bdda-8d60dd1a5b95.png">

**Comment by andergmartins** [comment]
I was able to replicate this bug when I have set a default address to be notified, plus added the same email address on the post settings.

I'm implementing a simple way to remove duplicated emails from the queue.
