### ISSUE TITLE
Possible to set "Date format", "Time format" and others to be blank in the settings

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#212]
It shouldn't be possible to save this as empty:

<img width="1136" alt="Screen Shot 2022-01-21 at 5 41 06 PM" src="https://user-images.githubusercontent.com/3868028/150609663-6d920167-9ad8-4e2d-a0f9-aa5d5d86a05c.png">

**Comment by andergmartins** [comment]
This is not a valid setting anymore, but we might apply the same fix to the Default formats: date and time

![image](https://github.com/user-attachments/assets/f908e1bc-40b7-46a0-80e3-1dd86fb5d8b6)

If allowing it to be blank, show a placeholder with a default format.
