### ISSUE TITLE
jQuery.fn.live() is deprecated

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#22]
https://wordpress.org/support/topic/jquery-fn-live-is-deprecated-2/

> this plugin needs to be updated as it is now using a deprecated jQuery function:v
> 
> /wp-content/plugins/post-expirator/admin-edit.js
> 
> jQuery.fn.live() is deprecated

**Comment by contactashish13** [comment]
@stevejburge I can't see this function being used anywhere in the code. Can you please verify in case I'm missing something?

**Comment by stevejburge** [comment]
@contactashish13 No worries. Closing for now.
