### ISSUE TITLE
Can we make the cron schedule more human-readable

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#231]
Here's the schedule:
![Screen Shot 2022-03-24 at 11 57 47 AM](https://user-images.githubusercontent.com/3868028/159958190-17151f29-d01a-4875-87ad-277907786df1.png)

Here's the expiration:
![Screen Shot 2022-03-24 at 11 58 09 AM](https://user-images.githubusercontent.com/3868028/159958278-d7c8bff0-2311-4442-aed8-e0d8b67e7cce.png)

Can we make the schedule more human readable? It's not possible for regular users to confirm this is correct

**Comment by andergmartins** [comment]
Move this to a new submenu item, and probably adding two submenus: Scheduled Actions, and Previous Actions
