### ISSUE TITLE
Cron fails if debug not turned on

### ISSUE THREAD

**Issue by dmschlot** [publishpress/PublishPress-Future#265]
Ran cron using wp-cli using:
sudo -u www-data -E -- wp --path=/var/www/html cron event run --due-now

Error
`PHP Fatal error:  Uncaught Error: Call to a member function save() on bool in /var/www/html/wp-content/plugins/post-expirator/post-expirator.php:804
Stack trace:
#0 /var/www/html/wp-includes/class-wp-hook.php(307): postexpirator_expire_post()
#1 /var/www/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#2 /var/www/html/wp-includes/plugin.php(524): WP_Hook->do_action()
#3 phar:///usr/local/bin/wp/vendor/wp-cli/cron-command/src/Cron_Event_Command.php(343): do_action_ref_array()
#4 phar:///usr/local/bin/wp/vendor/wp-cli/cron-command/src/Cron_Event_Command.php(265): Cron_Event_Command::run_event()
#5 [internal function]: Cron_Event_Command->run()
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(100): call_user_func()
#7 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}()
#8 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(491): call_user_func()
#9 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runn in /var/www/html/wp-content/plugins/post-expirator/post-expirator.php on line 804`

Looking at /var/www/html/wp-content/plugins/post-expirator/post-expirator.php:804
I see
`        $debug = postexpirator_debug(); // check for/load debug

        $id = (int)$id;

        $debug->save(array('message' => 'Called postexpirator_expire_post with id=' . $id));

        if (empty($id)) {
            if (POSTEXPIRATOR_DEBUG) {
                $debug->save(array('message' => 'No Post ID found - exiting'));
            }

            return false;
        }`

Reviewing the code clearly
` $debug->save(array('message' => 'Called postexpirator_expire_post with id=' . $id));`
needs to be change to
`if (POSTEXPIRATOR_DEBUG) {
    $debug->save(array('message' => 'Called postexpirator_expire_post with id=' . $id));
}`

(Just to note, I'd prefer `if ($debug !== false)` instead of checking POSTEXPIRATOR_DEBUG, but that wouldn't be consistent with what the rest of the plugin does, so to be consistent check POSTEXPIRATOR_DEBUG)

Current work around is to leave debug enabled (/wp-admin/admin.php?page=publishpress-future&tab=diagnostics)

**Comment by stevejburge** [comment]
Thanks for reporting that @dmschlot
