### ISSUE TITLE
"Cron event not found"

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#267]
I've tested and can confirm that 2.7.3 works great, but starting with 2.7.4 the plugin only shows "Cron event not found"

<img width="440" alt="Screen Shot 2022-06-13 at 7 35 18 AM" src="https://user-images.githubusercontent.com/3868028/173359815-d50b4052-ed4c-4648-b805-609dcbb90826.png">

**Comment by andergmartins** [comment]
@stevejburge this is probably caused by #265

**Comment by andergmartins** [comment]
I can confirm this was caused by #265. The expiration runs, but fails due the fatal error. But for WP it was already triggered, so the cron event is deleted. Since there was a fatal error on the expiration process, the data remains corrupted.
