### ISSUE TITLE
Can't enable expiring settings for posts using the classic editor

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Future#274]
If editing a post using the classic editor, I can't enable post expiration for the post. After checking the checkbox, and saving, the box returns unchecked.

This is failing on the test:

>Expiring posts using the Classic editor: When default expiration is not activated for post, I can enable it for an existent post

**Comment by andergmartins** [comment]
The problem is the default expiration date is set to a past hour, on the same day. Maybe because of a timezone issue? 

To replicate, set the post type setting for Default Date/Time Duration = None.
Then create a new post and try to activate. Check the date time. If you set a custom expiration interval, like "+1 week" the bug doesn't happen.

And it is saving indeed, but since the cron job is running right after the post is saved, it seems to be expiring, unchecking the box.

**Comment by andergmartins** [comment]
@stevejburge I think we could remove the “None” option on the Default Date/Time Duration, and convert it to Custom: "+1 week" as the default value. This avoid to the default date be the same date the post is created, and making it instantly expire, giving the impression it didn’t save (because after expiring the expiration settings are removed).

**Comment by stevejburge** [comment]
@andergmartins Yes, that makes sense. "None" has no use, right?

**Comment by andergmartins** [comment]
@stevejburge thanks. Right, there no real "None" under the hood. A date is always required so if "None" is selected, we use the current date time, what causes that buggy side-effect.

Ok, thanks, I will work on that.
