### ISSUE TITLE
Can't bulk edit CPT 

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Future#281]
ISSUE: Can't bulk edit CPT

Step to replicate:
1. Make sure you have a custom post type
2. Make sure you have PublishPress Future installed
3. On the PublishPress Future setting, disable the custom post type that you created in step 1
4. Try to bulk edit the custom post type such as add a category or something
5. Observe issue update button will do nothing.
6. Works fine when PublishPress future deactivated

https://wordpress.org/support/topic/plugin-causing-issue-with-woocommerce-bulk-edit/

**Comment by mjot** [comment]
I just applied the changes from the referenced commits to version 2.7.7 once and was able to fix the problem.

Thanks!

**Comment by andergmartins** [comment]
Thanks @mjot for the feedback
