### ISSUE TITLE
IT-FR translation updates

### ISSUE THREAD

**Issue by wocmultimedia** [publishpress/PublishPress-Future#283]
Hi,
Here's the updated IT/FR translations for the Future plugin.
[FUTURE-PostExpirator-IT-FR_translationUpdate_July2022.zip](https://github.com/publishpress/PublishPress-Future/files/9226888/FUTURE-PostExpirator-IT-FR_translationUpdate_July2022.zip)

Best,
Angelo

**Comment by wocmultimedia** [comment]
I made a full revision and update.
[FUTURE-PostExpirator-IT-FR_translationUpdate_August2022.zip](https://github.com/publishpress/PublishPress-Future/files/9246753/FUTURE-PostExpirator-IT-FR_translationUpdate_August2022.zip)
Best,
Angelo

**Comment by andergmartins** [comment]
Thanks @wocmultimedia

**Comment by andergmartins** [comment]
Duplicated by #297
