### ISSUE TITLE
ES-FR-IT Translations Updates November 2022

### ISSUE THREAD

**Issue by wocmultimedia** [publishpress/PublishPress-Future#308]
Hi,
Here's I have made the ES-FR-IT Translations Updates I have made today.
Please, add them to languages folder.
[post-expirator-Future_ES-FR-IT_TranslationUpdates_November2022.zip](https://github.com/publishpress/PublishPress-Future/files/9981739/post-expirator-Future_ES-FR-IT_TranslationUpdates_November2022.zip)

Thanks,
Angelo

**Comment by andergmartins** [comment]
Fixed on 26278bcf702332a6691827d2327c94878e63721c
