### ISSUE TITLE
Taxonomy expiration is not working

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Future#309]
Step to replicate:
1. Create new post
2. Add some category
3. Set expiration to taxonomy related (add, replace, or remove)
4. Publish

Observe issue, cron created, when the time comes, it did not fire anything, and there is cron event not found: 
![image](https://user-images.githubusercontent.com/83811723/201678754-d8c0a115-60b8-4d1e-a985-075010a0e3df.png)

Version 2.8
Works fine on 2.7.8 version

**Comment by stevejburge** [comment]
@rizaardiyanto1412 I'm not seeing this bug. Can we report more details .... PHP version, settings etc?

**Comment by rizaardiyanto1412** [comment]
PHP Version 7.4 

Setting just default one after install Future. Try on fresh WP installation.

**Comment by stevejburge** [comment]
@rizaardiyanto1412 Thanks. No luck with a fresh 7.4 in my testing.

What type of expiration are you using?

**Comment by rizaardiyanto1412** [comment]
@stevejburge Remove. See video attached for better view: https://www.loom.com/share/777e4c44377e446b898b6b60953b44c0

**Comment by andergmartins** [comment]
That seems to be related to default value for the settings, and happen when the settings for Post Types were never saved. 

I was able to replicate the bug some times, but after saving once the Post Types settings (wp-admin/admin.php?page=publishpress-future&tab=defaults) the issue is not reproducible anymore.

**Comment by stevejburge** [comment]
@andergmartins In my testing, I think you're correct

Saving the Post Types isn't something users will normally do, but it seems to solve the problem.

Is there a workaround we can add for new users?

**Comment by rizaardiyanto1412** [comment]
@stevejburge @andergmartins Should I tell the users to save Post Types setting for now? Or there will be a fix from our side?

**Comment by andergmartins** [comment]
@rizaardiyanto1412 that probably works as a workaround, yes you can recommend that to them. I'm still working on the fix.
