### ISSUE TITLE
Simplify setting to set default expiration date/time interval, #325

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Future#325]
![image](https://user-images.githubusercontent.com/83811723/209279015-b8a32f7a-61b8-48f9-9ccf-eb0fb00885ed.png)

This option is missing in 2.8 version.

**Comment by andergmartins** [comment]
@rizaardiyanto1412 we removed that by purpose, for this issue: https://github.com/publishpress/PublishPress-Future/issues/274

Did you receive a request from a user to restore that option? We don't think that option makes sense, but we might be missing specific use cases.

**Comment by rizaardiyanto1412** [comment]
@andergmartins Yes Anderson, this is the report: https://wordpress.org/support/topic/default-date-time/

**Comment by andergmartins** [comment]
Thanks @rizaardiyanto1412

**Comment by andergmartins** [comment]
Thanks @rizaardiyanto1412 I still don't see the point on restoring the "none" option. I would instead fix that label for something like “Set the default expiration date to be used when creating new posts and pages. Defaults to custom.”

In the past if "none" was selected the user would see the current date, which is a implicit default date anyway.

@stevejburge what do you think? Should we restore the "None" option for that field? I think the reported bug was not caused by that deprecated/missed option.

**Comment by rizaardiyanto1412** [comment]
@andergmartins I think you are correct. I thought it was bug before because I didn't know we had that previous issue. I agree to just fix the label until there is a report of real use case on "none"

**Comment by stevejburge** [comment]
@rizaardiyanto1412 @andergmartins Sounds good. Maybe this format?

<img width="1373" alt="Screen Shot 2023-01-05 at 10 06 43 AM" src="https://user-images.githubusercontent.com/3868028/210812720-aa4c84dd-f0e0-409e-8d71-964d52524f2d.png">

Would we also need to remove the "Publish Time" option from similar dropdowns?
<img width="875" alt="Screen Shot 2023-01-05 at 10 10 01 AM" src="https://user-images.githubusercontent.com/3868028/210812816-0aeebde5-14c8-4a12-bbfa-b5b40b182eae.png">

**Comment by andergmartins** [comment]
@stevejburge removing PublishTime, I agree we can use the format you sent. But that forces us to do a clean up on the Post Types tab as well. The post types have a similar option, and now only the "custom" option would make sense. I suggest we follow the same format there, removing the select box and adding the default value as placeholder if the Custom field is empty. If filled, that custom value is used. If empty, show the default value from Defaults tab as placeholder, interpreting that as "Inherit from General Settings" was selected.

How it is now, and how it would be if custom field is empty:

![Screenshot 2023-01-05 at 16 53 09](https://user-images.githubusercontent.com/407131/210868981-27a85f5c-4e7d-4735-979e-ef0a7ec0a47b.png)

![image](https://user-images.githubusercontent.com/407131/210869179-3b59ab10-5483-43dc-a0cc-cf3928320a52.png)

**Comment by stevejburge** [comment]
Thanks @andergmartins 

In your second image, would this box be automatically populated from the "Defaults" tab? 

If so, that sounds like a good plan

**Comment by andergmartins** [comment]
@stevejburge yes, it will be automatically populated, but as a placeholder, not the value itself. Cool, tks. I will finish that.
