### ISSUE TITLE
Bug with choosing a taxonomy change as a default

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#335]
I can confirm this error reported by a user.

- How to expire: choose a taxonomy option
- Auto-Enable?: yes
- There should be the option to choose the term(s) but that's missing

![Screen Shot 2023-01-10 at 5 12 50 PM](https://user-images.githubusercontent.com/3868028/211673810-a243f987-92c0-4916-a3cf-579f2bc157ed.png)

This produces an error when editing posts:

![Screen Shot 2023-01-10 at 5 13 04 PM](https://user-images.githubusercontent.com/3868028/211674253-e6324cb5-8e0c-4e9f-8187-7576164dbe88.png)

**Comment by andergmartins** [comment]
@stevejburge I can't replicate. Please, could you post what is the error message it displays in the console?

**Comment by andergmartins** [comment]
Thanks, here is another error message I found:

>react-dom.min.js?ver=17.0.1:9 TypeError: Cannot read properties of null (reading 'length')
    at t.value (gutenberg-panel.jsx:249:68)
    at t.value (gutenberg-panel.jsx:34:35)
    at jn (react-dom.min.js?ver=17.0.1:9:35117)
    at Wt (react-dom.min.js?ver=17.0.1:9:50532)
    at os (react-dom.min.js?ver=17.0.1:9:112194)
    at Ur (react-dom.min.js?ver=17.0.1:9:77643)
    at Ir (react-dom.min.js?ver=17.0.1:9:77571)
    at Dr (react-dom.min.js?ver=17.0.1:9:77434)
    at Pr (react-dom.min.js?ver=17.0.1:9:74429)
    at react-dom.min.js?ver=17.0.1:9:30173
rr @ react-dom.min.js?ver=17.0.1:9
t.payload @ react-dom.min.js?ver=17.0.1:9
Vn @ react-dom.min.js?ver=17.0.1:9
Wt @ react-dom.min.js?ver=17.0.1:9
os @ react-dom.min.js?ver=17.0.1:9
Ur @ react-dom.min.js?ver=17.0.1:9
Ir @ react-dom.min.js?ver=17.0.1:9
Dr @ react-dom.min.js?ver=17.0.1:9
Pr @ react-dom.min.js?ver=17.0.1:9
(anonymous) @ react-dom.min.js?ver=17.0.1:9
unstable_runWithPriority @ react.min.js?ver=17.0.1:9
xn @ react-dom.min.js?ver=17.0.1:9
Nn @ react-dom.min.js?ver=17.0.1:9
_n @ react-dom.min.js?ver=17.0.1:9
Er @ react-dom.min.js?ver=17.0.1:9
Rt @ react-dom.min.js?ver=17.0.1:9
e @ data.min.js?ver=d8cf5b24f99c64ae47d6:9
t @ data.min.js?ver=d8cf5b24f99c64ae47d6:9
(anonymous) @ data.min.js?ver=d8cf5b24f99c64ae47d6:2
(anonymous) @ data.min.js?ver=d8cf5b24f99c64ae47d6:2
p @ data.min.js?ver=d8cf5b24f99c64ae47d6:2
(anonymous) @ data.min.js?ver=d8cf5b24f99c64ae47d6:2
(anonymous) @ redux-routine.min.js?ver=c9ea6c0df793258797e6:9
(anonymous) @ data.min.js?ver=d8cf5b24f99c64ae47d6:2
(anonymous) @ data.min.js?ver=d8cf5b24f99c64ae47d6:2
(anonymous) @ data.min.js?ver=d8cf5b24f99c64ae47d6:2
(anonymous) @ core-data.min.js?ver=d8d458b31912f858bcdf:2
await in (anonymous) (async)
(anonymous) @ data.min.js?ver=d8cf5b24f99c64ae47d6:2
(anonymous) @ redux-routine.min.js?ver=c9ea6c0df793258797e6:9
(anonymous) @ data.min.js?ver=d8cf5b24f99c64ae47d6:2
(anonymous) @ data.min.js?ver=d8cf5b24f99c64ae47d6:2
ie @ data.min.js?ver=d8cf5b24f99c64ae47d6:2
(anonymous) @ data.min.js?ver=d8cf5b24f99c64ae47d6:2
setTimeout (async)
a @ data.min.js?ver=d8cf5b24f99c64ae47d6:2
i @ data.min.js?ver=d8cf5b24f99c64ae47d6:2
(anonymous) @ edit-post.min.js?ver=2baffbeec6cbe5171dee:7
(anonymous) @ data.min.js?ver=d8cf5b24f99c64ae47d6:9
l @ data.min.js?ver=d8cf5b24f99c64ae47d6:2
(anonymous) @ data.min.js?ver=d8cf5b24f99c64ae47d6:2
(anonymous) @ data.min.js?ver=d8cf5b24f99c64ae47d6:9
Ke @ data.min.js?ver=d8cf5b24f99c64ae47d6:9
vo @ edit-post.min.js?ver=2baffbeec6cbe5171dee:7
ct @ react-dom.min.js?ver=17.0.1:9
os @ react-dom.min.js?ver=17.0.1:9
Ur @ react-dom.min.js?ver=17.0.1:9
Ir @ react-dom.min.js?ver=17.0.1:9
Dr @ react-dom.min.js?ver=17.0.1:9
Pr @ react-dom.min.js?ver=17.0.1:9
Er @ react-dom.min.js?ver=17.0.1:9
ul @ react-dom.min.js?ver=17.0.1:9
(anonymous) @ react-dom.min.js?ver=17.0.1:9
Lr @ react-dom.min.js?ver=17.0.1:9
ml @ react-dom.min.js?ver=17.0.1:9
e.render @ react-dom.min.js?ver=17.0.1:9
Po @ edit-post.min.js?ver=2baffbeec6cbe5171dee:7
(anonymous) @ post-new.php:1824

That is related to this:

![Screenshot 2023-01-11 at 11 13 28](https://user-images.githubusercontent.com/407131/211828193-2f534d30-bc6f-4371-bdcb-1ce260a10af0.png)

`categproesNew` is `null`.

**Comment by andergmartins** [comment]
@stevejburge The error message is fixed now on the test site, but I agree we should have a field to optionally set default terms. I'm working on that.

**Comment by andergmartins** [comment]
Note to self: implemented on block editor, classic editor, and quick-edit. It is still missing the bulk-edit panel.
