### ISSUE TITLE
FR-IT Translation Updates January 2023

### ISSUE THREAD

**Issue by wocmultimedia** [publishpress/PublishPress-Future#336]
Hi, 
Here's copy of the files of FR-IT Translation Updates January 2023, please include them in language folder.
[Future_TranslationUpdates_FR-IT_January2023.zip](https://github.com/publishpress/PublishPress-Future/files/10394390/Future_TranslationUpdates_FR-IT_January2023.zip)

Thanks,
Angelo

**Comment by andergmartins** [comment]
Fixed on https://github.com/publishpress/PublishPress-Future/commit/fdb3a0a50751b00b3c9a3ecbd7ba716247f354c9
