### ISSUE TITLE
User Role does not work

### ISSUE THREAD

**Issue by faridalizade** [publishpress/PublishPress-Future#380]
Hello,

I use WCFM Multi Vendor Plugin. I set only Administrator on configurations but it seems Vendors are also see this when they publish product.

How can I hide Post Examinator from front end non admins please?

Thank you.

<img width="961" alt="Screen Shot 2023-01-28 at 19 39 10" src="https://user-images.githubusercontent.com/63564604/215275643-fa3a3b66-7a99-4941-ab93-aba13e044015.png">

**Comment by stevejburge** [comment]
Hi @faridalizade. Thanks for using PublishPress Future.

Github is for bug report, not general support questions. Those questions should be on the WordPress forums.

If you want to report a bug, please click "New Issue" and add the requested details.

**Comment by faridalizade** [comment]
Hi @stevejburge,

I think you are wrong with your fast closing ticket. Please check here #381. 

Thank you!
