### ISSUE TITLE
Created Date and also Action Date?

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#387]
We have the "Created Date" when the setting was added to the post.

Should we also have an "Action Date" to record when the action was made to the post?
<img width="1063" alt="Screenshot 2023-02-13 at 2 28 15 PM" src="https://user-images.githubusercontent.com/3868028/218555249-fcfb5c4d-0319-43aa-9a17-7c3ed9105f64.png">

**Comment by andergmartins** [comment]
@stevejburge that column displays the date the log was created, and means the date the action happened. We do not record the date the setting was added to the post but I think that might be a good one to have.

**Comment by stevejburge** [comment]
@andergmartins Thanks. Perhaps for a future release then? 

In this version, we can just change the title. Perhaps "Log Date" is best?

**Comment by andergmartins** [comment]
Sounds good, that would make it more clear for sure 👍🏻

**Comment by andergmartins** [comment]
@stevejburge I'm not sure this makes sense now that we are using the Actions Scheduler library and has a different log:

![image](https://github.com/publishpress/PublishPress-Future/assets/407131/6f63dbd2-d84e-4bf6-99ca-6b32a29efd77)

**Comment by stevejburge** [comment]
@andergmartins Agreed
