### ISSUE TITLE
Default expiry duration is broken for future years

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#39]
https://wordpress.org/support/topic/2-4-2-update-caused-year-not-to-behave/

![Screen Shot 2021-06-11 at 5 52 45 PM](https://user-images.githubusercontent.com/3868028/121752301-daa8a280-cadd-11eb-8430-f97cb7a40ea0.png)

I can confirm this isn't working for future years.

Sometimes it doesn't work. Sometimes it resets to 1970:

![Screen Shot 2021-06-11 at 5 49 27 PM](https://user-images.githubusercontent.com/3868028/121752064-62da7800-cadd-11eb-906c-fd74bf56c6ba.png)

**Comment by contactashish13** [comment]
@stevejburge I'm not sure you are supposed to add the double quotes to the box. It should be like this:

![image](https://user-images.githubusercontent.com/12953439/121837556-870fa200-ccf3-11eb-8f41-61344122aca4.png)

I realize the instructions could be considered confusing so I've made them a teeny bit better while fixing the bug.

PR: https://github.com/publishpress/PublishPress-Future/pull/41

**Comment by stevejburge** [comment]
@contactashish13 OK, let's be careful here.

We know 100% that some people are using quotes here

**Comment by contactashish13** [comment]
@stevejburge actually we don't have proof that anyone is using quotes inside the textbox. You did but are others too? If the feature has been working for them [before our changes](https://wordpress.org/support/topic/2-4-2-update-caused-year-not-to-behave/#post-14552511) in 2.4.2 caused the future year bug, then they are most probably not using quotes. 

I don't think this feature has any support for quotes or the code would have to strip out quotes before sending the string to strtime and I don't see any such code in any previous version:

Here is a snippet of the code from [v2.4.0](https://plugins.svn.wordpress.org/post-expirator/tags/2.4.0/post-expirator.php):

![image](https://user-images.githubusercontent.com/12953439/121990952-5182bb80-cdbc-11eb-9e93-0ebdcb655ac1.png)

And from [v2.3.1](https://plugins.svn.wordpress.org/post-expirator/tags/2.3.1/post-expirator.php):

![image](https://user-images.githubusercontent.com/12953439/121991066-8858d180-cdbc-11eb-9d6d-86a1c92d55d7.png)

Just to be doubly sure, I have rolled back to v2.4.1 and v2.4.0 using https://wordpress.org/plugins/wp-rollback/ and using quotes in the textbox defaults the date to 1970. Let me know in case I've missed out something obvious.

If you want to add support for quotes, maybe you can create a new issue for that?

**Comment by stevejburge** [comment]
@contactashish13 the current instructions are to use quotes. I think we need to assume 100% that people are using them, please

**Comment by contactashish13** [comment]
@stevejburge this is fixed by #41
