### ISSUE TITLE
All custom statuses show every post type

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#390]
This is on a site with WooCommerce installed.

I wonder how we stop these custom statuses showing on unrelated content?

<img width="332" alt="Screenshot 2023-02-15 at 8 37 58 AM" src="https://user-images.githubusercontent.com/3868028/219042770-66c32151-0665-41e0-9455-4cc00649580b.png">

**Comment by andergmartins** [comment]
Note for self: Add a checkbox on the Post Type settings panels: "Enable custom status control for this post type".

**Comment by stevejburge** [comment]
That's a good idea. This is a normal post if BBPress is installed:
<img width="325" alt="Screenshot 2023-02-16 at 3 10 27 PM" src="https://user-images.githubusercontent.com/3868028/219476312-b6ddf5ac-c9a6-4b31-90fb-68014e7fd499.png">

**Comment by stevejburge** [comment]
@andergmartins I think you may have the best solution there

By default, there's no way to determine which statuses are attached to which post types?

**Comment by stevejburge** [comment]
OK, thanks @andergmartins. Looks like your solution is the best then
