### ISSUE TITLE
Replace "Expiry" with "Actions"

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#392]
Working through the documentation, I think we should start to move the plugin towards new terminology: "Future Actions" rather than "Way to Expire" for example. Even now, most of the changes are not "expiry"

For example ....

Old: "Enable Post Expiration"
New: "Enable Future Actions"
<img width="585" alt="Screenshot 2023-02-16 at 1 55 21 PM" src="https://user-images.githubusercontent.com/3868028/219460906-7ad9854a-4eb6-4a76-9593-425622300bab.png">

Old: "How to Expire"
New: "Choose Future Action"

<img width="299" alt="Screenshot 2023-02-16 at 1 56 21 PM" src="https://user-images.githubusercontent.com/3868028/219461288-511f7092-da52-47fa-ac93-744e571b6707.png">

**Comment by andergmartins** [comment]
Add new capabilities mentioning the new term, but keep backward compatibility with the "expire" capabilities.
