### ISSUE TITLE
Field in quick edit should be switched in Deutsch language

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Future#405]
If the WordPress site using Deutch language, when you click quick edit on a post or page, the field from Future should be switched just like how WordPress doing

![image](https://user-images.githubusercontent.com/83811723/222154813-be6b2f54-b29e-4eff-9d55-9d7dba41f6f2.png)

Language: "German" (Deutsch) - DE

**Comment by andergmartins** [comment]
@stevejburge no DE translation provided yet for those terms. But I double checked and they are translatable. Nothing to fix in the plugin itself for now, just a missed translation string for that language. Btw, those terms changed a little in v3, so other languages will miss them until the translations are updated.
