### ISSUE TITLE
Post Expiration Options starting at UNIX time 0

### ISSUE THREAD

**Issue by scottydphillips** [publishpress/PublishPress-Future#406]
## Expected Behavior

I'm expecting to see the current time and date. That is displaying in the settings, but on an individual post, it is showing UNIX time 0.

## Current Behavior

Instead of giving me the current date and time I'm getting UNIX time 0. Being in US EST I'm seeing 12/31/1969 at 7:00 pm.

## Context

Our client has time-sensitive licenses on images that need to be taken down by a certain date. We were planning on using PublishPress Future to notify us when to take these images down. We have successfully used this in our local and development sites for this client but it is setting UNIX time 0 on production. I have manually disabled and enabled all other WordPress plugins to try and see if any of those were causing the issue, but that was not the case.

## Your Environment

* Version used: 2.9.1 & 2.9.2
* Browser Name and version: Chrome 110.0.5481.177
* PHP Version: 7.4
* WordPress Version: 5.9.5
* Operating System and version (desktop or mobile): macOS Ventura 13.1

## Screenshot of the posts display

![Screenshot 2023-02-28 at 2 43 10 PM](https://user-images.githubusercontent.com/84472741/222208557-ce8e88b2-b59b-48f8-b565-a7e19ddef13f.png)

## Screenshot of the settings menu

<img width="1170" alt="Screenshot 2023-02-28 at 4 37 13 PM" src="https://user-images.githubusercontent.com/84472741/222208769-ad1d33e3-fe76-4356-8c49-3cd01dc9be2b.png">

**Comment by stevejburge** [comment]
Hi  @scottydphillips. Thanks for using PublishPress Future. This one will be tricky for us to debug from the outside using Github. We don't have access to the server, or any other reports of this issue.

Our Pro support can request access and check the server. 

Otherwise, we'll need more debugging on your side, please. Do other servers work? If so, what's different with this server?

**Comment by scottydphillips** [comment]
We figured it out on our end. The post types were inheriting the dates incorrectly from the general settings. Thanks for your help!
