### ISSUE TITLE
Do we need the Recurrence and Log columns?

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#420]
![Screenshot 2023-03-30 at 3 48 27 PM](https://user-images.githubusercontent.com/3868028/228948423-5f57feff-8121-4e5c-a494-4c1661022756.png)

**Comment by andergmartins** [comment]
@stevejburge the Log column is important to understand what and when that happened. And if an error occurred it will be shown there. But we could make it hidden by default, but an important feature would be "hidden", but the user could enable it using the screen options anyway.

The column Recurrence is not used right now for our "expiration" actions. But it is important to mention any action for the plugin (even data migrations) will be displayed on that list. Some maintenance tasks can have recurrence. We have none right now, but that is a possibility. I would say lets remove the column and if a task is recurrent we show that info in the scheduled data column after the date?

And what about merging Action and Status columns? We could remove Status column and move the icon to before the action name. The icon title will have the status text for clarifying.

Here is a prototype:

![image](https://user-images.githubusercontent.com/407131/228976948-457f3be0-ba7e-425d-82c0-3f1bf54fc2a7.png)

**Comment by stevejburge** [comment]
Thanks @andergmartins. No worries. Maybe I'm over-thinking this. Perhaps it's best to leave these columns alone, particularly if this will be shared with other PublishPress plugins
