### ISSUE TITLE
Migration has one small error

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#423]
Updating an existing site to 3.0 seems to work except for this odd entry:

  | publishpress_future/v30000_migrate_wpcron_expirations [12]

![Screenshot 2023-03-30 at 3 59 45 PM](https://user-images.githubusercontent.com/3868028/228950895-018a8086-237a-4cd4-8ac9-ecef114c0d8b.png)

**Comment by andergmartins** [comment]
@stevejburge yes, that page was intended to display all the plugin activity, not only "expirations". I can improve the text displayed there for a human readable format.

But we have the option to create that entries on a different group, which would hide them from that page, but still show them on the Tools > Scheduled Actions screen.

What do you think? Improve text/display, or move it?

**Comment by andergmartins** [comment]
Btw, that action shows as failed... please, what is the log it displays on the last column?
