### ISSUE TITLE
Dutch Translation is missing

### ISSUE THREAD

**Issue by SimonvanWijhe** [publishpress/PublishPress-Future#429]
There is already a finished translation in Dutch available: https://translate.wordpress.org/projects/wp-plugins/post-expirator/stable/nl/default/

Would you like to add this to the project?

This would be much appreciated!

**Comment by andergmartins** [comment]
Thanks @SimonvanWijhe

**Comment by SimonvanWijhe** [comment]
Hi Anderson Grüdtner Martins,

Thanks for adding the Dutch translation!

The current [file](https://github.com/publishpress/PublishPress-Future/blob/main/languages/post-expirator-nl_NL.po) is only missing a lot of translations but this one up to date: https://translate.wordpress.org/projects/wp-plugins/post-expirator/stable/nl/default/

Thanks again for your efforts!
