### ISSUE TITLE
Placeholder on Auto enable is confusing

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Future#432]
![image](https://user-images.githubusercontent.com/83811723/232948850-25a3e7d2-c3dd-49fb-a86b-072ef14d4cc0.png)

> When the default date/time offset is set as a default in the Defaults tab, for example +1 week, it is also shown like that for posts in the Post Types tab as a placeholder in that field, which gives the impression that the default will be used when nothing is filled.
> 
> The default however is only used when auto-enable is disabled. When auto-enable is enabled it does not use the default tab set ‘default date/time offset’ (even though it still shows it as a placeholder), but it needs to be set manually.
> 
> I do wonder if this is either odd UI design with no proper explanation or indeed a bug.

Original thread: https://wordpress.org/support/topic/default-date-time-offset-not-working-with-video/

**Comment by rizaardiyanto1412** [comment]
Duplicate of https://github.com/publishpress/PublishPress-Future/issues/455

**Comment by andergmartins** [comment]
Just a note about the fix, it was indirectly fixed after implemented the changes required for the new Pro feature that allows to use the publishing date as the base for the post expiration.
