### ISSUE TITLE
Fatal error sending expiration email since version 2.9.0+

### ISSUE THREAD

**Issue by menno-ll** [publishpress/PublishPress-Future#433]
Since version 2.9.0, a new parameter `$expirationAction` has been added to the `sendEmail` function of the `ExpirablePostModel` class.
See https://github.com/publishpress/PublishPress-Future/blob/30c9a8b6f9e7842d482da9e95766c90c12ff74a2/src/Modules/Expirator/Models/ExpirablePostModel.php#L429

This causes a fatal error:
```
Too few arguments to function PublishPressFuture\Modules\Expirator\Models\ExpirablePostModel::sendEmail(), 1 passed in /path/to/wp-installation/wp-content/plugins/post-expirator/src/Modules/Expirator/Models/ExpirablePostModel.php on line 378 and exactly 2 expected
```

This happens because in the same `ExpirablePostModel` class, the `sendEmail` function is called without that parameter.
See https://github.com/publishpress/PublishPress-Future/blob/30c9a8b6f9e7842d482da9e95766c90c12ff74a2/src/Modules/Expirator/Models/ExpirablePostModel.php#L378

**Comment by andergmartins** [comment]
Thanks your help @menno-ll

**Comment by menno-ll** [comment]
Hi @andergmartins 
I see some changes have been made, nice!

One minor thing i've noticed is that passing a string for the `sendEmail ()` function now triggers a deprication notice.
Howevery in the plugin code this parameter is still passed with value `'Hey!'`. This happens in the `ExpirablePostModel` class.
