### ISSUE TITLE
Remove term action does not work

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Future#448]
Step to replicate:
1. Edit post
2. Enable future action
3. "Remove all terms and add new term"
4. Add your term
5. Observe issue
6. On the specified time, it will not work

**Comment by andergmartins** [comment]
@rizaardiyanto1412 I can't replicate this please could you try using the attached package?
[publishpress-future-3.0.1-beta.2.zip](https://github.com/publishpress/PublishPress-Future/files/11761876/publishpress-future-3.0.1-beta.2.zip)

**Comment by rizaardiyanto1412** [comment]
@andergmartins The above package did not solve the issue. I tried the latest release 3.0.1 and still face an issue.
I can provide test site.

**Comment by andergmartins** [comment]
@rizaardiyanto1412 ok, thanks. Please, could you record a short screencast showing you replicating the bug? I was not able to replicate based on the steps you described on the issue... I might be missing anything.

Thanks.

**Comment by rizaardiyanto1412** [comment]
@andergmartins This is the video to replicate the issue: https://www.loom.com/share/d2ba0cbb3b7b45f68d3506c394a03f57

**Comment by andergmartins** [comment]
@rizaardiyanto1412 thanks for the screencast. I still can't replicate it but I will try doing more testing.
Please, could you check if 3.0.3-beta.1 fixes the issue? (Available on the `#testing` channel.

**Comment by rizaardiyanto1412** [comment]
@andergmartins This does seems solved in 3.0.3-beta.1 version. I'll try to check with customer if the issue also resolved on their end

**Comment by andergmartins** [comment]
Awesome, thanks @rizaardiyanto1412
