### ISSUE TITLE
Improve settings UI

### ISSUE THREAD

**Issue by contactashish13** [publishpress/PublishPress-Future#45]
Use native WP look and feel without using any CSS framework.

@stevejburge I'm adding this as we had discussed last week. Can you please add this to the correct milestone?

**Comment by stevejburge** [comment]
@contactashish13 Thanks. That does look like good progress

Maybe in the future we can use new tabs for "Notifications" and "Footer Display". However, for now, small changes are best

**Comment by stevejburge** [comment]
@contactashish13 the new UI looks great, but can we use the standard WordPress tabs?

![Screen Shot 2021-08-18 at 9 38 23 AM](https://user-images.githubusercontent.com/3868028/129908102-991c5468-3396-4b3a-b484-589e7f1ff481.png)

![Screen Shot 2021-08-18 at 9 39 59 AM](https://user-images.githubusercontent.com/3868028/129908342-aae2eaa3-d797-4e0c-874d-b67d0d9a41fe.png)
