### ISSUE TITLE
Table ppfuture_actions_args is missed in PHP 8.2.3

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Future#450]
Plugin update works fine in php7.2 environment.

throw fatal error in php8.2.3 environment. Please see the error below.

```
[14-Jun-2023 05:36:03 UTC] PHP Fatal error: Uncaught mysqli_sql_exception: Table 'singlewpdbdev.wp_ppfuture_actions_args' doesn't exist in /var/www/html/current/www/wp-content/db.php:1404
Stack trace:

0 /var/www/html/current/www/wp-content/db.php(1404): mysqli_query()

1 /var/www/html/current/www/wp-content/db.php(942): hyperdb->ex_mysql_query()

2 /var/www/html/current/www/wp-includes/class-wpdb.php(3099): hyperdb->query()

3 /var/www/html/current/www/wp-admin/includes/upgrade.php(2797): wpdb->get_results()

4 /var/www/html/current/www/wp-content/plugins/post-expirator/src/Modules/Expirator/Schemas/ActionArgsSchema.php(58): dbDelta()

5 /var/www/html/current/www/wp-content/plugins/post-expirator/src/Modules/Expirator/Migrations/V30000WPCronToActionsScheduler.php(44): PublishPress\Future\Modules\Expirator\Schemas\ActionArgsSchema::createTableIfNotExists()

6 /var/www/html/current/www/wp-content/plugins/post-expirator/src/Modules/Settings/Controllers/Controller.php(363): PublishPress\Future\Modules\Expirator\Migrations\V30000WPCronToActionsScheduler->__construct()

7 [internal function]: PublishPress\Future\Modules\Settings\Controllers\Controller->initMigrations()

8 /var/www/html/current/www/wp-includes/class-wp-hook.php(308): call_user_func_array()

9 /var/www/html/current/www/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()

10 /var/www/html/current/www/wp-includes/plugin.php(517): WP_Hook->do_action()

11 /var/www/html/current/www/wp-settings.php(623): do_action()

12 /var/www/html/current/www/wp-config.php(85): require_once('…')

13 /var/www/html/current/www/wp-load.php(50): require_once('…')

14 /var/www/html/current/www/wp-cron.php(46): require_once('…')

15 {main}

thrown in /var/www/html/current/www/wp-content/db.php on line 1404
```

Related to https://wordpress.org/support/topic/failed-to-create-table-ppfuture_actions_args-in-php-8-2-3/

**Comment by rizaardiyanto1412** [comment]
Update from customer:

> Btw, it doesn’t seem to have issue in php8.2.
> So probably create table script or calling that function maybe deprecated in php8.2.3.

**Comment by andergmartins** [comment]
Just an update, I can replicate it on PHP 8.0.27, and I don't think it is related to the PHP version. If I delete the table `_ppfuture_action_args` and change the option `postexpiratorVersion` to `2.9.3` to force a data migration, I can see the error:

![image](https://github.com/publishpress/PublishPress-Future/assets/407131/0e6a0018-52f3-42f6-891c-7d4bf383be7b)

The problem seems to be related to the query `DESCRIBE <table>` being executed before the table is created. That do not avoid the table creation, but users will see the error once, or every time the migration run.

**Comment by andergmartins** [comment]
`dbDelta` runs a `DESCRIBE` query on the table that is not created yet, and that triggers the error I described above. We are suppressing errors for now on that query and changing the order of migrations run.
