### ISSUE TITLE
Error message with custom statuses

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#453]
I was updating this guide:
https://publishpress.com/knowledge-base/custom-statuses-future/

I tested with the Free version of Future and saw this error:
<img width="601" alt="Screenshot 2023-06-14 at 11 53 33 AM" src="https://github.com/publishpress/PublishPress-Future/assets/3868028/8aaeb82e-7cbd-4cfb-a55f-fa15a982c79f">

**Comment by stevejburge** [comment]
Update: this happens with Future Pro too

**Comment by andergmartins** [comment]
@stevejburge I can't replicate both issues: the warning, and non-visible custom statuses. 
Regarding the custom statuses, please could you double check if you had enabled them in the post type settings?

![image](https://github.com/publishpress/PublishPress-Future/assets/407131/293a8d37-20b4-40b5-a6dd-01d51ac68faa)

**Comment by andergmartins** [comment]
But I committed a workaround for the PHP warning you reported.

**Comment by andergmartins** [comment]
Closing this for now. I suppose if we receive new reports, the workaround will help us to debug the issue without breaking those sites.
