### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function getDynamicLabel(

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#454]
Reported here: https://wordpress.org/support/topic/fatal-error-when-updating-to-3-0

Fatal error: Uncaught Error: Call to a member function getDynamicLabel() on null in /home/public_html/*/wp-content/plugins/post-expirator/src/Views/expire-column.php:35 Stack trace: #0 /home/public_html/***/wp-content/plugins/post-expirator/legacy/classes/Display.class.php(422): include() #1 /home/public_html/***/wp-content/plugins/post-expirator/legacy/functions.php(210): PostExpirator_Display->render_template(‘expire-column’, Array) #2 /home/public_html/***/wp-includes/class-wp-hook.php(310): postexpirator_show_value(‘expirationdate’) #3 /home/public_html/***/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(”, Array) #4 /home/public_html/***/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #5 /home/public_html/***/wp-admin/includes/class-wp-posts-list-table.php(1351): in /home/public_html/***/wp-content/plugins/post-expirator/src/Views/expire-column.php on line 35

**Comment by stevejburge** [comment]
We've had a second report of this: https://wordpress.org/support/topic/uncaught-error-in-3-0-1/

**Comment by andergmartins** [comment]
I was only able to replicate this after I deactivate the Pro plugin and try to load data in the Free plugin that was defined by Pro. On that case, future actions like change the post status to a custom status is only available in Pro. If I schedule one action to a post, them deactivate the Pro plugin, the Free plugin can't handle it and will display corrupted output.

I'm adding a better message and I hope we will be able to confirm if that was the cause.
