### ISSUE TITLE
Make all Quick Edit boxes required

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#46]
It should not be possible to leave any of these date boxes empty.

Alternatively, we can use the WordPress date picker: https://github.com/publishpress/PublishPress-Future/issues/10

<img width="500" alt="Screen Shot 2021-06-16 at 10 12 57 AM" src="https://user-images.githubusercontent.com/3868028/122235159-77c35c80-ce8b-11eb-9dc8-3233084af4ac.png">

**Comment by contactashish13** [comment]
@stevejburge in WP core if any element in the date field below is empty it defaults to the current date, the current year, midnight (00 hours) or 00 minutes. It does not mandate any field as required.

![image](https://user-images.githubusercontent.com/12953439/122329804-a7d43380-cf4f-11eb-9ab5-8b08f53cf6bc.png)

I'm following the same principle in PR https://github.com/publishpress/PublishPress-Future/pull/49 and also added placeholders that indicate what those default values will be:

![image](https://user-images.githubusercontent.com/12953439/122329753-90954600-cf4f-11eb-9a87-3208637de158.png)

Let me know in case you still want to enforce the required field.

As a side note, we cannot use the datepicker that comes in the block editor (#10) inside the quick/bulk edit screen but we can definitely use [another library that does not depend on any other libraries](https://flatpickr.js.org/examples/) or [something more popular that even Advanced Custom Field uses](https://github.com/trentrichardson/jQuery-Timepicker-Addon)

**Comment by stevejburge** [comment]
@contactashish13 Good idea on the placeholder. Let's do that and skip the "required" option

**Comment by contactashish13** [comment]
@stevejburge this is fixed by #49
