### ISSUE TITLE
Uncaught Error: Class not found

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Future#461]
After updating to 3.0.0, we received the WordPress “Your Site is Experiencing a Technical Issue” email from all the sites we manage that use PublishPress.

Here’s the error info…

```
An error of type E_ERROR was caused in line 12 of the file
REDACTED/wp-content/plugins/post-
expirator/src/Modules/Expirator/Models/CurrentUserModel.php.
Error message: Uncaught Error: Class
"PublishPress\Future\Framework\WordPress\Models\CurrentUserModel"
not found in REDACTED/wp-content/plugins/post
expirator/src/Modules/Expirator/Models/CurrentUserModel.php:

```
Original report: https://wordpress.org/support/topic/error-message-uncaught-error-class-after-update-to-3-0-0/

**Comment by andergmartins** [comment]
>Thanks [@nathaningram](https://wordpress.org/support/users/nathaningram/). So the sites are up and working, but you’re getting emails about this error?

> No, just one email upon update of the plugin.
>We are getting this in the error_log in wp-admin since the update though…
>[06-Jun-2023 12:43:25 UTC] PHP Warning: Attempt to read property “term_id” on array in /REDACTED/wp-content/plugins/post-expirator/legacy/functions.php on line 1080

**Comment by andergmartins** [comment]
This was the only report for the error that happened only once to the client, and I can't replicate it using the current dev version. I'm closing this and we can reopen if someone else reports this again.

**Comment by andergmartins** [comment]
I'm reopening this because we got another report:

https://wordpress.org/support/topic/critical-php-error-on-release-3-0-6/
