### ISSUE TITLE
PublishPress Future menus are now displaiy in English no more in French

### ISSUE THREAD

**Issue by Patrick3378** [publishpress/PublishPress-Future#464]
* Version used: 3.0.1
* Browser Name and version: PublishPress Future 3.0.1

Menus was good in french with release 2.9.2
![menu_autoriser](https://github.com/publishpress/PublishPress-Future/assets/136922775/f46fe208-ebda-42d7-aa9b-3be92ef08a0d)
![status](https://github.com/publishpress/PublishPress-Future/assets/136922775/92aa9cd7-c2ee-4238-9290-7607e01802a4)

**Comment by stevejburge** [comment]
@Patrick3378 When new text strings are added to a plugin, it can take a few days for the translations to be updated
