### ISSUE TITLE
Two small errors with Gutenberg metabox

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#465]
- No spacing under the "Reset" button
- "Terms" label has an unnecessary ()
<img width="1360" alt="Screenshot 2023-06-19 at 10 40 23 AM" src="https://github.com/publishpress/PublishPress-Future/assets/3868028/c83dd340-4b82-4476-9fd1-ff0cd7acd49c">

**Comment by andergmartins** [comment]
Spacing issue is fixed. The "terms" label was fixed on 3.0.4.
