### ISSUE TITLE
Future-FREE_TranslationUpdates_ES-IT_June2023

### ISSUE THREAD

**Issue by wocmultimedia** [publishpress/PublishPress-Future#466]
Hi,
I have made the ES and IT translation updates for Feature Free. Below find a copy of the files to be added to plugin languages folder.
[Future-FREE_TranslationUpdates_ES-IT_June2023.zip](https://github.com/publishpress/PublishPress-Future/files/11789542/Future-FREE_TranslationUpdates_ES-IT_June2023.zip)
I used the .pot file inside the folder of latest release to update the language files.
Thanks,
Angelo

**Comment by andergmartins** [comment]
Thanks @wocmultimedia files added to the languages folder.
