### ISSUE TITLE
add multiple actions to bulk edit, support for default values for date and year

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#47]
Same request as https://github.com/publishpress/PublishPress-Future/issues/46

We may also want to add a checkbox to enable Post Expirator. This is a frustrating feature in Bulk Edit: "Will only update expiration date if already configured on post."

<img width="500" alt="Screen Shot 2021-06-16 at 10 12 57 AM" src="https://user-images.githubusercontent.com/3868028/122235918-118b0980-ce8c-11eb-8a65-9ed7c6f8f004.png">

**Comment by contactashish13** [comment]
@stevejburge 

> We may also want to add a checkbox to enable Post Expirator. This is a frustrating feature in Bulk Edit: "Will only update expiration date if already configured on post."

For this I see 4 options when using bulk edit. The ones checked are already supported in the existing code:
- [x] do not change 
- [x] change expiry for posts that have this set 
- [ ] change expiry for posts that have this set AND add expiry for those that do not have this set 
- [ ] only add expiry for those that do not have this set 

For this do you think something like this makes sense?

![image](https://user-images.githubusercontent.com/12953439/122337898-92193b00-cf5c-11eb-88e0-2c8007c05922.png)

**Comment by stevejburge** [comment]
thanks @contactashish13 

I think adding the third option makes sense as the default:
"change expiry for posts that have this set AND add expiry for those that do not have this set"

My feeling is, if someone has checked a box for a post in "Bulk Edit" they want to set an expiry date for it.

**Comment by contactashish13** [comment]
@stevejburge I'm not sure this should be part of 2.4.4 as #47, which fixes this, has already been merged. 

PS - Can you please review the others marked for 2.4.4 as I see others that have been merged/fixed already?

**Comment by stevejburge** [comment]
@contactashish13 Which ones do you think are merged/fixed already?

You're welcome to close them
