### ISSUE TITLE
Undefined action. Warning: Action scheduled but its definition is not available anymore.

### ISSUE THREAD

**Issue by sforeman** [publishpress/PublishPress-Future#474]
## Versions of software with this bug
I am running PublishPress Future version 3.0.2 on two websites that are at WP version 6.2.2. They use different themes, but have many plugins in common.

## Expected Behavior

Create a post and set a future expiration date/time and then publish it.
Expected behavior - post is published, a relevant message appears in the "Future Actions" column in the list of posts, and the post is "unpublished" at the expiration date/time.

## Current Behavior

The post is published, but the "Future Actions" column shows the error message: "Action scheduled but its definition is not available anymore. Did you disable the plugin that defined it?"

## Possible Solution

I do not know enough about how the plugin works to suggest a solution.

## Steps to Reproduce (for bugs)

1. Create a new post and put some information into it.
2. Set an expiration date/time for the post using PublishPress-Future
3. Publish the post
4. View the list of posts
5. Wait until after the expiration time and view the post

## Context

It is not possible to set a post to disappear after its period of validity. This means, for example, that special offers remain listed after they have expired.

## Your Environment

WordPress 6.2.2

**Comment by stevejburge** [comment]
One more report: https://wordpress.org/support/topic/plugin-crashes-after-3-0-2-update/

**Comment by stevejburge** [comment]
4th https://wordpress.org/support/topic/definition-not-available-anymore/

**Comment by andergmartins** [comment]
I was able to replicate this one using Gutenberg. 
![image](https://github.com/publishpress/PublishPress-Future/assets/407131/fccbc986-be77-450d-891d-bf4117979f4e)

The register on table `_ppfuture_actions_args` for that expiration is missing the `expireType` value: 

```
{"expireType":"","category":[],"categoryTaxonomy":"","enabled":true,"date":1687361482}
```
![image](https://github.com/publishpress/PublishPress-Future/assets/407131/5b2e6792-91ea-4d10-867e-0fa62d4ed354)

**Comment by andergmartins** [comment]
It seems the default future action is not recognized by the Gutenberg component.

## How to replicate

1. edit or add a new post
2. enable future action, but do not change the way it should expire. Leave the default value.
3. save draft or publish
4. go to the posts list

You might see the warning on that post.

Now, if I do the same, but before saving I select a different future action and save, the issue doesn’t happen.

**Comment by andergmartins** [comment]
Opening Gutenberg I see that empty `expireType` is an issue in the API:

![image](https://github.com/publishpress/PublishPress-Future/assets/407131/c0bb76f1-8708-4f0c-85c4-7da02669b053)
