### ISSUE TITLE
The “postexpirator-sidebar” plugin has encountered an error and cannot be rendered.

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Future#475]
I face this issue on local, but it really hard to replicate it. 

Even I migrate the same site to InstaWP but I could not replicate it there. 

On my local, this fixed by deactivate Woocommerce

https://github.com/publishpress/PublishPress-Future/assets/83811723/66e5e89b-e56c-4c58-b89f-e8acf6ff6113

![image](https://github.com/publishpress/PublishPress-Future/assets/83811723/19341b47-2e18-4fe5-ab23-cafda750c246)

There is other user face this issue as well: https://wordpress.org/support/topic/plugin-crashes-after-3-0-2-update/

**Comment by andergmartins** [comment]
Note to self: This can be related to #474. It shows a different side effect, but the errors happens because the variable `expirationAction` is empty. A similar issue happens for the other ticket, but on the PHP side.

**Comment by andergmartins** [comment]
@rizaardiyanto1412 did you see the error using the Free or Pro version of Future?

**Comment by andergmartins** [comment]
Never mind, I was able to replicate it using WooCommerce and the Free version of the Plugin, thanks

**Comment by rizaardiyanto1412** [comment]
Thanks @andergmartins I'm glad you are able to replicate it.
Yes, I think it happens only once. Because sometime I could not replicate it anymore

**Comment by andergmartins** [comment]
It seems like this was fixed by the patch for #474. I'm closing this one and we can reopen if needed.

**Comment by stevejburge** [comment]
Possible fix in this beta version:
[publishpress-future-3.0.3-beta.1.zip](https://github.com/publishpress/PublishPress-Future/files/11804094/publishpress-future-3.0.3-beta.1.zip)
