### ISSUE TITLE
Incongruence with file pot

### ISSUE THREAD

**Issue by wocmultimedia** [publishpress/PublishPress-Future#480]
Hi @andergmartins @htmgarcia @stevejburge  ,
I have found an incongruence between the file pot inside the languages folder and the translation files inside the same folder as well as the main WP folder in my local machine. I just updated the plugin to latest release.
Please, let me know if with latest release did you change the string quantity.
Because the new file pot has 199 strings, the post-expirator-it_IT.po  147 strings that I updated yesterday with previous file pot and the post-expirator-it_IT.po in the main WP content> langiages>plugins folder has 203 strings.
Can you tell me, what do I have to do? Which one is correct, the file pot or what?
Thanks

**Comment by andergmartins** [comment]
@wocmultimedia Sorry for the confusion. We are planning to adjust our workflow for fixing that. Before releasing, this is probably going to be the new workflow:

* Update the .pot file
* Update/sync translation files based on new .pot file
* Send updated translation files to be updated
* Wrap up the release

New pre-release packages would be generated from Monday to Thursday, then we send for translating (3rd step), planning the releases for next Monday or Tuesday. Do you think that makes sense? Does that work for you?

**Comment by wocmultimedia** [comment]
Hi @andergmartins ,
I think it's a good workflow! 
Because my concern were two so far:
-The current release had the translations one version back
- I didn't like to make you pay again for the same translation because I had to update twice or trice it.

We will give a better impression to user if we can release a plugin complete and up to date.
Yes, the correct workflow should be that as you wrote, once you have got the final plugin code then:
-  you create a new pot file which should be the leading file in any case
- you make update/sync translation files based to this new pot file (optionally)
- wrap in a pre-release package and send it to us with a specific message titled "FOR TRANSLATORS" because we almost don't read the heap of message we usually receive during the day from GitHub.
- Give us two/three days to arrange the translations and send you the updated files or the package as you prefer, but ready to publish/release

**Comment by andergmartins** [comment]
Thanks @wocmultimedia that sounds like a plan. 
We are going to create an issue with FOR TRANSLATORS in the title, and assign to you, attaching the package when we are ready.

**Comment by wocmultimedia** [comment]
> Thanks @wocmultimedia that sounds like a plan. We are going to create an issue with FOR TRANSLATORS in the title, and assign to you, attaching the package when we are ready.

Together we are a great team of indiscutible professionals

**Comment by andergmartins** [comment]
Thanks, we appreciate your help.
