### ISSUE TITLE
Improve the label for the terms field in the block editor panel

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Future#483]
Instead of having "Terms (<taxonomy)" we could have the plural name of the taxonomy only: "Categories" for example.

![image](https://github.com/publishpress/PublishPress-Future/assets/407131/f1d82d56-4799-4a92-9a9e-76a957d9d4b2)

![image](https://github.com/publishpress/PublishPress-Future/assets/407131/1fa151ec-72bc-44b3-a428-69bdc08243ee)

**Comment by andergmartins** [comment]
@stevejburge what are your thoughts? Do you prefer "Terms (TAXONOMY-NAME)" or just "TAXONOMY-PLURAL-NAME"?

**Comment by stevejburge** [comment]
Thanks @andergmartins 

I think some Taxonomy names may be long, so let's save space with "TAXONOMY-PLURAL-NAME"?

We can have two equal titles for the two boxes:
ACTION
TAXONOMY-PLURAL-NAME
