### ISSUE TITLE
Issue of incompatibility Feature PRO languages files

### ISSUE THREAD

**Issue by wocmultimedia** [publishpress/PublishPress-Future#493]
Hi,
I'm sorry to point out that there is an issue with file POT in Future Pro 3.0.4.
I updated the plugin tonight and in my local machine I found out this situation as you can see from shots below

1. File pot inside languages folder has 21 strings
2. Translation files ES-IT-FR inside languages folder have 23 strings
3. in the main WP folder Future-pro IT translation and others have 375 strings
 What is correct? What is my reference for updating translations?
![FuturePRO_IT_Translation_InsideTheFolder](https://github.com/publishpress/PublishPress-Future/assets/2352240/7816665a-00e8-4ef9-ab94-b4505b8a4331)
![MainWP_FuturePRO_IT_Translation](https://github.com/publishpress/PublishPress-Future/assets/2352240/9c485c28-b1b9-4c17-8600-e93c2b7f533a)
![NewPotFile_inside_FuturePro](https://github.com/publishpress/PublishPress-Future/assets/2352240/d75c1027-702f-426c-8350-79b22f0976a5)

**Comment by andergmartins** [comment]
Note to self: double check strings with the free text domain: 'post-expirator'

**Comment by andergmartins** [comment]
@wocmultimedia please, use .pot as the reference 👍🏻  I just updated it on the branch `3.0-branch`, and uploaded new files attached here.

[publishpress-future-pro-language.zip](https://github.com/publishpress/PublishPress-Future/files/12084000/publishpress-future-pro-language.zip)

**Comment by wocmultimedia** [comment]
Hi @andergmartins,
I updated the files using your zip file. Here's the copy of files. Please, paste them into the languages folder.
[PublishPress_FuturePRO-TranslationUpdates-ES-FR-IT-18July2023.zip](https://github.com/publishpress/PublishPress-Future/files/12088254/PublishPress_FuturePRO-TranslationUpdates-ES-FR-IT-18July2023.zip)
Thanks,
Angelo
