### ISSUE TITLE
Translation bug

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#5]
> The value of day of the week not translate posts meta panel.
> Traslate is OK on the plugin setting.

> The people of translation project was advised to change the source code of “day of the week” for translation.
> core code
> https://build.trac.wordpress.org/browser/trunk/wp-includes/class-wp-locale.php?marks=120#L120

https://wordpress.org/support/topic/the-value-of-day-of-the-week-not-translate-posts-meta-panel/

**Comment by contactashish13** [comment]
@stevejburge I'm not sure I understand what this error implies. I don't see day of the week anywhere in the plugin. Can you please share the steps to reproduce this?

**Comment by stevejburge** [comment]
Thanks @contactashish13. I've asked the original reporter to follow-up here

**Comment by stevejburge** [comment]
@contactashish13 More details on this:
https://ibb.co/7rDgwky

![Zrzut-ekranu-2021-06-04-192844](https://user-images.githubusercontent.com/3868028/121083439-6e603300-c7ad-11eb-8a9d-58dee0882460.jpg)

**Comment by stevejburge** [comment]
Here's my version in Spanish:
<img width="966" alt="Screen Shot 2021-06-07 at 4 30 36 PM" src="https://user-images.githubusercontent.com/3868028/121083697-c0a15400-c7ad-11eb-92f3-4b97db826eb7.png">

**Comment by contactashish13** [comment]
@stevejburge this is fixed by #33
