### ISSUE TITLE
Support for custom taxonomies

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#50]
This would be a useful feature in the upcoming Pro version:

> I’m also trying to set a default category to be added from a custom taxonomy. In the settings there’s only an option for default categories on normal Posts but not on custom post types.

https://wordpress.org/support/topic/default-expiration-custom-field/#post-14566845

**Comment by stevejburge** [comment]
One more report: https://wordpress.org/support/topic/custom-taxonomy-not-showing-in-post-expirator/

**Comment by stevejburge** [comment]
> We have a custom taxonomy applied to Pages. In PublishPress Future settings for pages,[it sees the custom tax but on the page itself the category add/remove/replace options aren't present
![Annotation on 2022-08-02 at 10-57-22](https://user-images.githubusercontent.com/3868028/182454646-8e59ceb2-d2aa-4298-a78b-c74ff1136f1d.png)
<img width="801" alt="Markup 2022-08-02 at 10 56 29" src="https://user-images.githubusercontent.com/3868028/182454649-baf950ee-29b5-480f-a27b-4d981f704e39.png">

**Comment by stevejburge** [comment]
No luck with the Alpha

I made a taxonomy with the TaxoPress plugin.

I checked yes for "Can terms in this taxonomy be organized into hierarchical relationships?"
<img width="621" alt="Screen Shot 2022-08-17 at 11 04 31 AM" src="https://user-images.githubusercontent.com/3868028/185174577-37c306c8-8320-4766-91fb-f751c6a90260.png">

I choose this new taxonomy in the Future settings:
<img width="786" alt="Screen Shot 2022-08-17 at 11 05 49 AM" src="https://user-images.githubusercontent.com/3868028/185174838-4376d9cd-679f-4773-84a3-3c74ff7657b9.png">
 
It shows successfully in the admin area:
<img width="574" alt="Screen Shot 2022-08-17 at 11 06 16 AM" src="https://user-images.githubusercontent.com/3868028/185175069-28a7cbad-896f-46bd-81ed-864140d06145.png">

However, on expiry:

<img width="591" alt="Screen Shot 2022-08-17 at 11 07 14 AM" src="https://user-images.githubusercontent.com/3868028/185175167-2c8917fd-0d2e-4134-a046-abd739f8e4b5.png">

**Comment by stevejburge** [comment]
@andergmartins you can see the same thing if you try to add or remove WooCommerce Product Categories for example:
<img width="549" alt="Screen Shot 2022-08-17 at 11 13 36 AM" src="https://user-images.githubusercontent.com/3868028/185176649-e235ae13-ccec-4829-83d7-ce60d5e91cb3.png">

**Comment by stevejburge** [comment]
@andergmartins Testing this out, I think it happens with all taxonomies in the alpha version, even Categories and Tags

**Comment by andergmartins** [comment]
@stevejburge thanks for the detailed instructions. But I still can't replicate the bug. Please, could you try making sure the expiration date is a few days in the future?

**Comment by stevejburge** [comment]
@andergmartins We may have ended up mixing two problems.

Problem #1. Custom taxonomies can show on Posts, but I'm having no luck getting them to show on Pages. I'm using TaxoPress to add a taxonomy to both:

<img width="665" alt="Screen Shot 2022-08-30 at 11 08 57 AM" src="https://user-images.githubusercontent.com/3868028/187473487-b802aef0-cefe-47ca-b3ce-ac064c71a792.png">

On Pages, the custom taxonomy is just missing:

<img width="316" alt="Screen Shot 2022-08-30 at 11 09 47 AM" src="https://user-images.githubusercontent.com/3868028/187473696-ef16e06d-4f71-4739-b1d9-3ca440ac280a.png">

Problem #2 might be a little hard to test a few days in the future. This appears only after the expiry time has passed:

<img width="425" alt="Screen Shot 2022-08-30 at 11 12 45 AM" src="https://user-images.githubusercontent.com/3868028/187474300-794f7660-eebf-452c-9000-062285356d71.png">

**Comment by andergmartins** [comment]
@stevejburge Ah! Thanks! And sorry, I was really missing a point you made clear before about custom post types. I can replicate the first problem and will check the second one later.
