### ISSUE TITLE
Error with post metabox

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#503]
I get an immediate error on this with the metabox
<img width="340" alt="Screenshot 2023-07-16 at 9 27 27 AM" src="https://github.com/publishpress/PublishPress-Future/assets/3868028/b1b2a9ba-a779-4566-ab87-91014f59bfe0">
<img width="980" alt="Screenshot 2023-07-16 at 9 27 59 AM" src="https://github.com/publishpress/PublishPress-Future/assets/3868028/8a44ec6e-4b14-4280-9bfa-c0ae85c9da78">

HN/I</<@https://nted-tapir-juye.instawp.xyz/wp-includes/js/dist/components.min.js?ver=bf6e0ec3089253604b52:32:463165
HN/I<@https://nted-tapir-juye.instawp.xyz/wp-includes/js/dist/components.min.js?ver=bf6e0ec3089253604b52:32:463311
useMemo@https://nted-tapir-juye.instawp.xyz/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:115389
t/e.useMemo@https://nted-tapir-juye.instawp.xyz/wp-includes/js/dist/vendor/react.min.js?ver=18.2.0:10:9875
HN@https://nted-tapir-juye.instawp.xyz/wp-includes/js/dist/components.min.js?ver=bf6e0ec3089253604b52:32:463037
yI@https://nted-tapir-juye.instawp.xyz/wp-includes/js/dist/components.min.js?ver=bf6e0ec3089253604b52:32:491480

**Comment by stevejburge** [comment]
Update: I think this is more than the metabox.

If I active Future by default for a post type, this same error occurs

**Comment by andergmartins** [comment]
Note to self: this is related to the "Invalid date" issue in the beta package.
