### ISSUE TITLE
Release notes of v3.0.0 is missing changed namespace

### ISSUE THREAD

**Issue by menno-ll** [publishpress/PublishPress-Future#508]
If you have found a bug in the code of our plugins and want to report it, this is the best place! 

However, please note that this option is for genuine bugs that can be reproduced on other sites. This is not for support questions about your site. We will close questions if they are about issues with your site.

We have "PublishPress members" support available for commercial users and "Non-members" support for non-commercial users: https://publishpress.com/publishpress-support/

## Expected Behavior

The changelog includes a namespace change from `PublishPressFuture` to `PublishPress\Future`

## Current Behavior

The changelog includes no namespace change

## Possible Solution

Add The following to the changes of v3.0.0:

```
CHANGED: Namespace has been changed from `PublishPressFuture` to `PublishPress\Future`;
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

I wanted to migrate my themes code to work with version 3 of this plugin.
Because I'm using some classes of this plugin, my code crashes as a change in namespaces wat not documented in the changelog.

## Your Environment

* Version used: 3.0.0 and 3.0.4
* Browser Name and version: Google Chrome Version 114.0.5735.198 (Official Build) (x86_64)
* Operating System and version (desktop or mobile): MacOS Ventura 13.4.1 (c) (22F770820d)
* Link to your project:

**Comment by andergmartins** [comment]
Thanks @menno-ll you're right we missed mentioning that in the changelogs and probably on some documentation. We are going to fix it.

But we did add class_aliases for the changed classes. Please, could you let us know what class broke so we can make sure that is fixed?

We are going to review the aliases, anyway. They are set in the `deprecated.php` file.

**Comment by menno-ll** [comment]
Hi @andergmartins , it's actually my VSCode extension "PHP Intelephense" that didn't detect the class aliases. It just indicated classes didn't exist, and because of that (and the fact i've never seen class aliases before, so didn't know this was a thing in PHP) I assumed that it would crash my old code. I've just after PHP Intelephense noticed the namespace changes fixed them all immediately by looking up then new namespace and replacing it, and only then tested if everything worked as expected again.

So to conclude, the code in the plugin doesn't crash, and in fact the class_alias function works as expected. Only my VSCode extension was in the wrong. My complements for you for making it more backward compatible than needed, even for a V3 release. And for the quick replies, highly appriciated!

Kind regards,
Menno

**Comment by andergmartins** [comment]
@menno-ll Oh, got it, thanks for the feedback. No problem, we appreciate your help.
Something to note is the aliases, and classes are now loaded in a hook to the action `plugins_loaded`, priority 10. So if any custom code tries to reference an alias, or class before that hook runs, it will fail anyway. We do need to mention that in the changelog. 

Thanks!
