### ISSUE TITLE
FOR TRANSLATORS: Update ES, FR, IT, NL translations

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Future#509]
The files are in the following ZIP:

[publishpress-future-free.zip](https://github.com/publishpress/PublishPress-Future/files/12089332/publishpress-future-free.zip)

.pot file is updated.

Please, let us know if you have any questions, thanks.

**Comment by andergmartins** [comment]
Related to #480

**Comment by andergmartins** [comment]
Hi @wocmultimedia, just following up to check if you had a chance to check the translation files, since this is the first issue we created assigning you, instead of mentioning as before. Thanks.

**Comment by wocmultimedia** [comment]
Hi @andergmartins ,
I'm sorry but I haven't received the notice by email or I mismatched.. I just downloaded and I check soon the translation to update.

**Comment by andergmartins** [comment]
Thanks @wocmultimedia, sounds like a plan. Sorry for missing that.
