### ISSUE TITLE
Bug Status should change to 'Trash' after performing 'Publish Press Future' action

### ISSUE THREAD

**Issue by jayadhivya** [publishpress/PublishPress-Future#510]
## Expected Behavior
                Perform the 'Publish Press Future' action on a WordPress.
                The status of the post should change to 'Trash' after the action is completed.
![Trash](https://github.com/publishpress/PublishPress-Future/assets/109314692/2adfd151-ce1f-4e09-9cc6-863c9d077cbe)

## Current Behavior
                 After performing the 'Publish Press Future' action on a WordPress, the status does not change to 'Trash'. And the post is disappeared.
![Trash1](https://github.com/publishpress/PublishPress-Future/assets/109314692/6a7d64d9-ddf3-4da4-bf77-2d4e737cda2d)

## Possible Solution
                 One possible solution to address this issue is to check the code logic or workflow associated with the 'Publish Press Future' action and investigate why the status is not being updated correctly. It may involve debugging the code or identifying any potential issues in the logic flow. Additionally, verifying the permissions and access levels for performing this action could also be considered.

## Steps to Reproduce (for bugs)

1. Go to http://localhost/wordpress/wp-admin/post.php?post=42&action=edit 
2. Open the "WordPress" feature in your application or plugin.
3. Select a specific press or article that is scheduled for future publication
4. Perform the necessary actions to initiate the "Change Action" feature.
5. Locate the "Change Action" dropdown or button that allows you to modify the action for the selected press.
6. Choose the "Trash" option from the available actions.
7. Confirm the selection or save the changes, if prompted.
8. Verify the press status or action after performing the "Change Action to Trash."
9. Observe and note the behavior or outcome of the action.
10. Record any discrepancies between the expected behavior (changing the action to "Trash") and the actual behavior observed.

## Context
          The Post should be changed in to 'Trash' but unfortunately it was disappeared I mean deleted automatically.

* Version used: 
* Browser Name and version: Google Chrome and 114.0.5735.199
* Operating System and version (desktop or mobile): Windows 11 and 22H2 (Laptop)
* Link to your project: http://localhost/wordpress/wp-admin/edit.php?post_type=post

**Comment by stevejburge** [comment]
@jayadhivya Thanks for reporting this. I don't see in our testing.

Can you try one more time?

What do you see if you go to Future > Settings?

<img width="1275" alt="Screenshot 2023-07-19 at 6 01 15 PM" src="https://github.com/publishpress/PublishPress-Future/assets/3868028/dde5d5e5-b392-4396-a116-8b597d64723f">

**Comment by jayadhivya** [comment]
@stevejburge I have attached screenshot for your reference. Please let me know further.
![Bug](https://github.com/publishpress/PublishPress-Future/assets/109314692/0d6a4ee9-b6ac-49ae-9f10-72e38fa48ccf)

**Comment by stevejburge** [comment]
@jayadhivya Sorry, wrong screenshot. I'm asking for what you see if you go to Future > Settings?
