### ISSUE TITLE
"Cron event scheduled" message

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#511]
I'm not sure this tooltip is helpful any more?
<img width="450" alt="Screenshot 2023-07-20 at 9 21 35 AM" src="https://github.com/publishpress/PublishPress-Future/assets/3868028/9bb55c93-1beb-4452-854b-3c8d6abae4ce">

**Comment by andergmartins** [comment]
I agree, let's remove it for now.
