### ISSUE TITLE
Updates to Italian translation for Future PRO July 30-2023

### ISSUE THREAD

**Issue by wocmultimedia** [publishpress/PublishPress-Future#524]
Hi @andergmartins, @htmgarcia ,

I updated the Italian translation for Future Pro because there were 3 typos and I corrected them.
[Publishpress-futurePRO-it_IT-NewUpdate-July30-2023.zip](https://github.com/publishpress/PublishPress-Future/files/12208821/Publishpress-futurePRO-it_IT-NewUpdate-July30-2023.zip)
Please, update the languages folder before releasing the 3.0.6
Thank you
Angelo

**Comment by andergmartins** [comment]
Thanks @wocmultimedia 🙏🏻
