### ISSUE TITLE
Function as_has_scheduled_action not found

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Future#529]
This bug was not replicated yet, but we had 2 reports about that.

```
Fatal error: Uncaught Error: Call to undefined function PublishPress\Future\Modules\Expirator\Adapters\as_has_scheduled_action() in /Applications/MAMP/htdocs/OFN/wp-content/plugins/post-expirator/src/Modules/Expirator/Adapters/CronToWooActionSchedulerAdapter.php:57 Stack trace:
#0 /Applications/MAMP/htdocs/OFN/wp-content/plugins/post-expirator/src/Modules/Expirator/ExpirationScheduler.php(165): PublishPress\Future\Modules\Expirator\Adapters\CronToWooActionSchedulerAdapter->postHasScheduledActions(55273)
#1 /Applications/MAMP/htdocs/OFN/wp-content/plugins/post-expirator/src/Modules/Expirator/Models/ExpirablePostModel.php(326): PublishPress\Future\Modules\Expirator\ExpirationScheduler->postIsScheduled(55273) 
#2 /Applications/MAMP/htdocs/OFN/wp-content/plugins/post-expirator/src/Modules/Expirator/Models/ExpirablePostModel.php(166): PublishPress\Future\Modules\Expirator\Models\ExpirablePostModel->isExpirationEnabled()
#3 /Applications/MAMP/htdocs/OFN/wp-content/plugins/post-expirator/legacy/functions.php(178): PublishPress\Fu in /Applications/MAMP/htdocs/OFN/wp-content/plugins/post-expirator/src/Modules/Expirator/Adapters/CronToWooActionSchedulerAdapter.php on line 57
```

From the other user:

```
In the error logs, i get the following error messages:
stderr: 
PHP Fatal error: Uncaught Error: Call to undefined function PublishPress\Future\Modules\Expirator\Adapters\as_has_scheduled_action() in /home/rrr/www/rrrr.net/_fl5eck/wp-content/plugins/post-expirator/src/Modules/Expirator/Adapters/CronToWooActionSchedulerAdapter.php:57, referer https://onetinfo.ch/_flueck/wp-admin/update-core.php?action=do-plugin-upgrade

Version:
WordPress: 6.2.2
PHP: 8.2
PublishPress Future: 3.0.6

```

**Comment by andergmartins** [comment]
I can't replicate this on the 3.1.0 branch. We will need to release and see if they still has the issue.

**Comment by ARomanofsky** [comment]
I get this in the ADMIN, if and only if i have the plugin WooCommerce Smart Coupons enabled also. 


Fatal error: Uncaught Error: Call to undefined function PublishPress\Future\Modules\Expirator\Adapters\as_has_scheduled_action()
in /var/www/vhosts/opp.allaroundcreative.net/stage/wp-content/plugins/post-expirator/src/Modules/Expirator/Adapters/CronToWooActionSchedulerAdapter.php on line 57

Call stack:

    PublishPress\F\M\E\A\CronToWooActionSchedulerAdapter::postHasScheduledActions()
    wp-content/plugins/post-expirator/src/Modules/Expirator/ExpirationScheduler.php:200
    PublishPress\F\M\E\ExpirationScheduler::postIsScheduled()
    wp-content/plugins/post-expirator/src/Modules/Expirator/Models/ExpirablePostModel.php:291
    PublishPress\F\M\E\M\ExpirablePostModel::isExpirationEnabled()
    wp-content/plugins/post-expirator/src/Views/expire-column.php:16
    include()
    wp-content/plugins/post-expirator/legacy/classes/Display.class.php:424
    PostExpirator_Display::render_template()
    wp-content/plugins/post-expirator/src/Modules/Expirator/Controllers/PostListController.php:99
    PublishPress\F\M\E\C\PostListController::renderColumn()
    wp-content/plugins/post-expirator/src/Modules/Expirator/Controllers/PostListController.php:82
    PublishPress\F\M\E\C\PostListController::managePostsCustomColumn()
    wp-includes/class-wp-hook.php:326
    WP_Hook::apply_filters()
    wp-includes/class-wp-hook.php:348
    WP_Hook::do_action()
    wp-includes/plugin.php:517
    do_action()
    wp-admin/includes/class-wp-posts-list-table.php:1380
    WP_Posts_List_Table::column_default()
    wp-admin/includes/class-wp-list-table.php:1799
    WP_List_Table::single_row_columns()
    wp-admin/includes/class-wp-posts-list-table.php:1432
    WP_Posts_List_Table::single_row()
    wp-admin/includes/class-wp-posts-list-table.php:834
    WP_Posts_List_Table::_display_rows()
    wp-admin/includes/class-wp-posts-list-table.php:810
    WP_Posts_List_Table::display_rows()
    wp-admin/includes/class-wp-list-table.php:1709
    WP_List_Table::display_rows_or_placeholder()
    wp-admin/includes/class-wp-list-table.php:1636
    WP_List_Table::display()
    wp-admin/edit.php:503

Query Monitor
