### ISSUE TITLE
JS error when admin user has no permissions

### ISSUE THREAD

**Issue by raphaelheying** [publishpress/PublishPress-Future#533]
![image](https://github.com/publishpress/PublishPress-Future/assets/11423862/102f19ff-151e-4d1f-815e-d10f6473b428)

When accessing the editing of a post using a user without permission to expire posts, a javascript error is generated.

The error happens in the expirator-classic-editor.js file, on line 16 calling the jQuery function val() of an element that doesn’t exist.

My suggestion to fix it would be not to load the script if the user doesn't have permissions, adding the following code in the enqueueScripts function of the /src/Modules/Expirator/Module.php file:

    public function enqueueScripts()
    {
	    $currentUserModelFactory = $this->currentUserModelFactory;
	    $currentUserModel = $currentUserModelFactory();
		
	    if (! $currentUserModel->userCanExpirePosts()) {
	        return;
	    }
           
        ...
     }

**Comment by andergmartins** [comment]
Thanks @raphaelheying for reporting the issue and suggesting a good solution.
