### ISSUE TITLE
Future Free Translation Updates v. 3.1.1

### ISSUE THREAD

**Issue by wocmultimedia** [publishpress/PublishPress-Future#551]
Hi @stevejburge, @htmgarcia, @andergmartins,
I updated the translations for Future Free v.3.1.1.
Here's copy of the files to add to plugin languages folder 
[Future-FREE_ES-FR-IT_TranslationUpdates_v311.zip](https://github.com/publishpress/PublishPress-Future/files/12928199/Future-FREE_ES-FR-IT_TranslationUpdates_v311.zip)

Thanks,
Angelo

**Comment by andergmartins** [comment]
Thanks @wocmultimedia
