### ISSUE TITLE
Strange years in the year selector

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Future#568]
We still can't replicate it on our machines, but several users reported that.

https://wordpress.org/support/topic/strange-years-in-the-year-selector/

One of the reports: 

>I’ve noticed the exact same thing this morning with new posts. The year dropdown for us on ‘only some posts’ shows dates showing in the range of 1749 to 1759 – we’ve seen other showing 0878 to -0888. We are using the same settings we’ve been using for months, to expire by removing a category. Obviously, if we use the year settings shown, the post expires immediately.
>
>If we clone the post, sometimes we get the new random dates and sometimes we get the correct dates. We’ve never seen this before and have not changed our processes or the types of posts in any way.

![2023-11-13_104153](https://github.com/publishpress/PublishPress-Future/assets/407131/5110e290-8d67-4441-b300-c1059a0874db)
![2023-11-13_104834](https://github.com/publishpress/PublishPress-Future/assets/407131/4a8b90f9-3c90-4a68-8260-a36a79a88e5a)

**Comment by philbirnie** [comment]
Here's the issue: 

1. The code in `ExpirablePostsModel` is running `strtotime` on a value that's already a timestamp (1st image)
2. As a result, we're getting strange values (2nd image).
3. A potential solution (commented out in the image) that appears to resolve the issue: 

```php
    /**
     * @return int|false
     */
    public function getExpirationDateAsUnixTime()
    {
        $this->expirationDate = $this->getExpirationDateString();

        return is_int($this->expirationDate) ? $this->expirationDate : (int)strtotime($this->expirationDate);
    }

````

<img width="1124" alt="Post Expirator Bug" src="https://github.com/publishpress/PublishPress-Future/assets/688818/72882d95-026f-4e92-90c6-4c468ce6ba5f">

<img width="1015" alt="Bug-result" src="https://github.com/publishpress/PublishPress-Future/assets/688818/d117243f-a8a4-410c-8329-978d578ad0f2">

**Comment by andergmartins** [comment]
Thanks @philbirnie for the contribution.
