### ISSUE TITLE
Use dates on changelogs

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#59]
Let's include the release date in the changelog:
<img width="660" alt="Screen Shot 2021-07-08 at 12 52 30 PM" src="https://user-images.githubusercontent.com/3868028/124961386-66352680-dfeb-11eb-9d6c-d2e2199fd48a.png">

**Comment by contactashish13** [comment]
@stevejburge I guess this is something to be taken care of when we release. Maybe we can remove it from the milestones and pin the issue so that this is not overlooked?

**Comment by stevejburge** [comment]
@contactashish13 Sure thing
