### ISSUE TITLE
Database is not updating with scheduled info

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#6]
I can confirm this in testing

> Post expirator breaks when an already post is setup with an expiration date that is edited to extend the date. Post expires on original date and not newly edited date. I am going to assume there will be no support for this as it seems this support channel is dead.

https://wordpress.org/support/topic/edited-post-expiry-dates-expiring-on-original-date/

**Comment by contactashish13** [comment]
@stevejburge could this be related to #4? I was able to see this happen only once and that too while using the quick edit function. I have not been able to replicate this again even after switching the debug mode inside the plugin.

Additionally, I have encountered another bug a couple of times when the expiration job is not created at all but once it is created it seems to get updated correctly (except for the one instance above).

PS - I have created #20 related to this.
