### ISSUE TITLE
Plugin conflict with WCFM

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#60]
Not a big deal, but let's check quickly to make sure it's not reflecting a larger issue:
https://wordpress.org/support/topic/wcfm-and-post-expirator-conflict/

**Comment by contactashish13** [comment]
@stevejburge I've added the function WCFM expects `_postExpiratorExpireType` as a legacy wrapper (cf. #40). That should fix the issue. PR https://github.com/publishpress/PublishPress-Future/pull/64

**Comment by stevejburge** [comment]
@contactashish13 Nicely done, thanks
