### ISSUE TITLE
"Show Classic Editor style box" option

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#604]
I think we broke the "Show Classic Editor style box" option
![Screenshot 2023-12-13 at 8 07 11 PM](https://github.com/publishpress/PublishPress-Future/assets/3868028/d93929c7-5b3a-482c-9962-fefbe1293809)

**Comment by stevejburge** [comment]
@rizaardiyanto1412 good point

@andergmartins Maybe we remove this feature and just offer the new style of box?

**Comment by andergmartins** [comment]
@stevejburge Yes, I agree. I missed that... there is no reason for that setting, now that we have similar boxes for the classic-metabox and Gutenberg plugin.
