### ISSUE TITLE
Move Date format and Time format to "Display" tab

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#605]
I think we broke the Date format and Time format options
![Screenshot 2023-12-13 at 8 11 50 PM](https://github.com/publishpress/PublishPress-Future/assets/3868028/cd58b290-3b60-4104-beb9-c02fff1dde61)

**Comment by rizaardiyanto1412** [comment]
![image](https://github.com/publishpress/PublishPress-Future/assets/83811723/da1c4c53-e8c6-4ae9-921e-8efabe9ae942)
![image](https://github.com/publishpress/PublishPress-Future/assets/83811723/63926382-dd99-441f-afcf-713eb3d00327)


Whats broke about this @stevejburge ? I did not face any issue with this date and time format

**Comment by stevejburge** [comment]
@rizaardiyanto1412 Sorry, you're right. I was doing late night testing.

Maybe we need to move these items under a "Shortcode" tab
