### ISSUE TITLE
Reports that the posts screen is broken

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#606]
Looks like the first specific report here: https://wordpress.org/support/topic/extension-loading-error-e_error-in-settingsposttypesmodel-php-line-41-3-1-4/

**Comment by paragonconsultants** [comment]
I've got the same problem the latest update has crashed two sites with same error on both frontend and back end

**Comment by rizaardiyanto1412** [comment]
Most of the user faced this issue:
https://wordpress.org/support/topic/version-4-1-4-crashed-my-site/

Full report:
`Error Details
=============
An error of type E_ERROR was caused in line 41 of the file /home1/akdlt/public_html/bracttakka/wp-content/plugins/post-expirator/src/Modules/Settings/Models/SettingsPostTypesModel.php. Error message: Uncaught TypeError: array_map(): Argument #2 ($array) must be of type array, string given in /home1/akdlt/public_html/bracttakka/wp-content/plugins/post-expirator/src/Modules/Settings/Models/SettingsPostTypesModel.php:41
Stack trace:
#0 /home1/akdlt/public_html/bracttakka/wp-content/plugins/post-expirator/src/Modules/Settings/Models/SettingsPostTypesModel.php(41): array_map('intval', '65,85,96')
#1 /home1/akdlt/public_html/bracttakka/wp-content/plugins/post-expirator/src/Modules/Expirator/Models/PostTypesModel.php(29): PublishPress\Future\Modules\Settings\Models\SettingsPostTypesModel->getPostTypesSettings()
#2 /home1/akdlt/public_html/bracttakka/wp-content/plugins/post-expirator/src/Modules/Expirator/Controllers/BulkActionController.php(68): PublishPress\Future\Modules\Expirator\Models\PostTypesModel->getActivatedPostTypes()
#3 /home1/akdlt/public_html/bracttakka/wp-content/plugins/post-expirator/src/Modules/Expirator/Controllers/BulkActionController.php(55): PublishPress\Future\Modules\Expirator\Controllers\BulkActionController->addHooks()
#4 /home1/akdlt/public_html/bracttakka/wp-content/plugins/post-expirator/src/Modules/Expirator/Module.php(128): PublishPress\Future\Modules\Expirator\Controllers\BulkActionController->initialize()
#5 /home1/akdlt/public_html/bracttakka/wp-content/plugins/post-expirator/src/Core/Plugin.php(115): PublishPress\Future\Modules\Expirator\Module->initialize()
#6 /home1/akdlt/public_html/bracttakka/wp-content/plugins/post-expirator/src/Core/Plugin.php(108): PublishPress\Future\Core\Plugin->initializeModules()
#7 /home1/akdlt/public_html/bracttakka/wp-content/plugins/post-expirator/post-expirator.php(126): PublishPress\Future\Core\Plugin->initialize()
#8 /home1/akdlt/public_html/bracttakka/wp-includes/class-wp-hook.php(322): PublishPress\Future\{closure}()
#9 /home1/akdlt/public_html/bracttakka/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#10 /home1/akdlt/public_html/bracttakka/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#11 /home1/akdlt/public_html/bracttakka/wp-settings.php(643): do_action('init')
#12 /home1/akdlt/public_html/bracttakka/wp-config.php(101): require_once('/home1/akdlt...')
#13 /home1/akdlt/public_html/bracttakka/wp-load.php(50): require_once('/home1/akdlt...')
#14 /home1/akdlt/public_html/bracttakka/wp-login.php(12): require('/home1/akdlt...')
#15 {main}
  thrown`

**Comment by andergmartins** [comment]
Thanks, @paragonconsultants, and sorry for the inconvenience.
We might have a new release today addressing that issue.

**Comment by andergmartins** [comment]
Just for future reference, this can be replicated editing the options table, changing the option `expirationdateDefaultsPost` to:

```
a:7:{s:10:"expireType";s:5:"draft";s:8:"taxonomy";s:8:"category";s:13:"activeMetaBox";s:1:"1";s:17:"emailnotification";s:0:"";s:19:"default-expire-type";s:6:"custom";s:19:"default-custom-date";s:0:"";s:5:"terms";s:5:"1,3,5";}
```

Then try opening the posts screen.
