### ISSUE TITLE
Wordpress Current version: 6.4.2 Failes with the Future plugin v 3.1.4

### ISSUE THREAD

**Issue by spawnmarvel** [publishpress/PublishPress-Future#607]
<!--- Your issue may already be reported!
First of all thanks for a great plugin.

## Expected Behavior

Wordpress panel had a message on update plugin PublishPress Future.
Assumed the site and plugi work work after update

## Current Behavior

Wordpress panel had a message on update plugin PublishPress Future.
I did the update and the white screen was instant. Not possible to view the website.

## Solution
Remove plugin folder post-expirator in wp-content\plugins
rm -r post-expirator
Wordpress sites works as expected again

## Steps to Reproduce (for bugs)

1. Update plugin
2. White screen
3. rm -r post-expirator
4. Wordpress sites works as expected again

## Your Environment

* 3.1.0 of future has worked for a long time, 3.1.4 failed on update
* Ubuntu OS
* Wordpress Current version: 6.4.2
* PHP 8.1.2-1ubuntu2.14 (cli) (built: Aug 18 2023 11:41:11) (NTS)

## Log

sudo cat apache2/error.log

[Thu Dec 14 09:42:25.958584 2023] [php:error] [pid 1031056] [client xxx.xx.x.xx:59446] PHP Fatal error:  Uncaught TypeError: array_map(): Argument #2 ($array) must be of type array, 
string given in /var/www/html/wordpress/wp-content/plugins/post-expirator/src/Modules/Settings/Models/SettingsPostTypesModel.php:41
\nStack trace:\n#0 /var/www/html/wordpress/wp-content/plugins/post-expirator/src/Modules/Settings/Models/SettingsPostTypesModel.php(41): 
array_map()\n#1 /var/www/html/wordpress/wp-content/plugins/post-expirator/src/Modules/Expirator/Models/PostTypesModel.php(29): 
PublishPress\\Future\\Modules\\Settings\\Models\\SettingsPostTypesModel->getPostTypesSettings()\n#2 
/var/www/html/wordpress/wp-content/plugins/post-expirator/src/Modules/Expirator/Controllers/BulkActionController.php(68): 
PublishPress\\Future\\Modules\\Expirator\\Models\\PostTypesModel->getActivatedPostTypes()\n#3 
/var/www/html/wordpress/wp-content/plugins/post-expirator/src/Modules/Expirator/Controllers/BulkActionController.php(55): 
PublishPress\\Future\\Modules\\Expirator\\Controllers\\BulkActionController->addHooks()\n#4 
/var/www/html/wordpress/wp-content/plugins/post-expirator/src/Modules/Expirator/Module.php(128): 
PublishPress\\Future\\Modules\\Expirator\\Controllers\\BulkActionController->initialize()\n#5 /var/www/html/wordpress/wp-content/plugins/post-expirator/src/Core/Plugin.php(115): 
PublishPress\\Future\\Modules\\Expirator\\Module->initialize()\n#6 /var/www/html/wordpress/wp-content/plugins/post-expirator/src/Core/Plugin.php(108): 
PublishPress\\Future\\Core\\Plugin->initializeModules()\n#7 /var/www/html/wordpress/wp-content/plugins/post-expirator/post-expirator.php(126): 
PublishPress\\Future\\Core\\Plugin->initialize()\n#8 /var/www/html/wordpress/wp-includes/class-wp-hook.php(322): PublishPress\\Future\\{closure}()\n#9 
/var/www/html/wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()\n#10 /var/www/html/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action()\n#11 
/var/www/html/wordpress/wp-settings.php(643): do_action()\n#12 /var/www/html/wordpress/wp-config.php(96): require_once('...')\n#13 /var/www/html/wordpress/wp-load.php(50): 
require_once('...')\n#14 /var/www/html/wordpress/wp-admin/admin.php(34): require_once('...')\n#15 /var/www/html/wordpress/wp-admin/site-health.php(10): 
require_once('...')\n#16 {main}\n  thrown in /var/www/html/wordpress/wp-content/plugins/post-expirator/src/Modules/Settings/Models/SettingsPostTypesModel.php on line 41, 
referer: https://mywe-url.domain/wp-admin/plugins.php

**Comment by spawnmarvel** [comment]
All my text is gone, args. I will add it again.

**Comment by spawnmarvel** [comment]
Wordpress Current version: 6.4.2 Failes with the Future plugin v 3.1.4

Env:
WP Current version: 6.4.2
PHP 8.1.2-1ubuntu2.14 (cli) (built: Aug 18 2023 11:41:11) (NTS)
Ubuntu:

Steps:
Went to admin and did an update of the plugin from 3.1.0, to 3.1.4 and the white screen came.
Logged in to ubuntu and did an rm -r post-expirator and the site came live again.
Did this 2 times and the same result each time.

Log:

[Thu Dec 14 09:42:25.958584 2023] [php:error] [pid 1031056] [client xxx.xx.x.xx:59446] PHP Fatal error:  Uncaught TypeError: array_map(): Argument #2 ($array) must be of type array, 
string given in /var/www/html/wordpress/wp-content/plugins/post-expirator/src/Modules/Settings/Models/SettingsPostTypesModel.php:41
\nStack trace:\n#0 /var/www/html/wordpress/wp-content/plugins/post-expirator/src/Modules/Settings/Models/SettingsPostTypesModel.php(41): 
array_map()\n#1 /var/www/html/wordpress/wp-content/plugins/post-expirator/src/Modules/Expirator/Models/PostTypesModel.php(29): 
PublishPress\\Future\\Modules\\Settings\\Models\\SettingsPostTypesModel->getPostTypesSettings()\n#2 
/var/www/html/wordpress/wp-content/plugins/post-expirator/src/Modules/Expirator/Controllers/BulkActionController.php(68): 
PublishPress\\Future\\Modules\\Expirator\\Models\\PostTypesModel->getActivatedPostTypes()\n#3 
/var/www/html/wordpress/wp-content/plugins/post-expirator/src/Modules/Expirator/Controllers/BulkActionController.php(55): 
PublishPress\\Future\\Modules\\Expirator\\Controllers\\BulkActionController->addHooks()\n#4 
/var/www/html/wordpress/wp-content/plugins/post-expirator/src/Modules/Expirator/Module.php(128): 
PublishPress\\Future\\Modules\\Expirator\\Controllers\\BulkActionController->initialize()\n#5 /var/www/html/wordpress/wp-content/plugins/post-expirator/src/Core/Plugin.php(115): 
PublishPress\\Future\\Modules\\Expirator\\Module->initialize()\n#6 /var/www/html/wordpress/wp-content/plugins/post-expirator/src/Core/Plugin.php(108): 
PublishPress\\Future\\Core\\Plugin->initializeModules()\n#7 /var/www/html/wordpress/wp-content/plugins/post-expirator/post-expirator.php(126): 
PublishPress\\Future\\Core\\Plugin->initialize()\n#8 /var/www/html/wordpress/wp-includes/class-wp-hook.php(322): PublishPress\\Future\\{closure}()\n#9 
/var/www/html/wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()\n#10 /var/www/html/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action()\n#11 
/var/www/html/wordpress/wp-settings.php(643): do_action()\n#12 /var/www/html/wordpress/wp-config.php(96): require_once('...')\n#13 /var/www/html/wordpress/wp-load.php(50): 
require_once('...')\n#14 /var/www/html/wordpress/wp-admin/admin.php(34): require_once('...')\n#15 /var/www/html/wordpress/wp-admin/site-health.php(10): 
require_once('...')\n#16 {main}\n  thrown in /var/www/html/wordpress/wp-content/plugins/post-expirator/src/Modules/Settings/Models/SettingsPostTypesModel.php on line 41,

**Comment by kronzo** [comment]
also on my site:
`Fatal error: Uncaught Error: array_map(): Argument #2 ($array) must be of type array, string given
in .../wp-content/plugins/post-expirator/src/Modules/Settings/Models/SettingsPostTypesModel.php on line 41

Call stack:

    array_map()
    wp-content/plugins/post-expirator/src/Modules/Settings/Models/SettingsPostTypesModel.php:41
    PublishPress\F\M\S\M\SettingsPostTypesModel::getPostTypesSettings()
    wp-content/plugins/post-expirator/src/Modules/Expirator/Models/PostTypesModel.php:29
    PublishPress\F\M\E\M\PostTypesModel::getActivatedPostTypes()
    wp-content/plugins/post-expirator/src/Modules/Expirator/Controllers/BulkActionController.php:68
    PublishPress\F\M\E\C\BulkActionController::addHooks()
    wp-content/plugins/post-expirator/src/Modules/Expirator/Controllers/BulkActionController.php:55
    PublishPress\F\M\E\C\BulkActionController::initialize()
    wp-content/plugins/post-expirator/src/Modules/Expirator/Module.php:128
    PublishPress\F\M\E\Module::initialize()
    wp-content/plugins/post-expirator/src/Core/Plugin.php:115
    PublishPress\F\C\Plugin::initializeModules()
    wp-content/plugins/post-expirator/src/Core/Plugin.php:108
    PublishPress\F\C\Plugin::initialize()
    wp-content/plugins/post-expirator/post-expirator.php:126
    PublishPress\Future\{closure}()
    wp-includes/class-wp-hook.php:322
    WP_Hook::apply_filters()
    wp-includes/class-wp-hook.php:348
    WP_Hook::do_action()
    wp-includes/plugin.php:517
    do_action()
    wp-settings.php:643
    require_once()
    wp-config.php:127
    require_once()
    wp-load.php:50
    require_once()
    wp-admin/admin.php:34
    require_once()
    wp-admin/plugins.php:10`

**Comment by spawnmarvel** [comment]
Hi @andergmartins thanks for the quick reply.
Do you know when this updated version will be available (pushed) in WordPress admin->add new plugin tab?
Regards

**Comment by andergmartins** [comment]
Hi @spawnmarvel it was released this afternoon
