### ISSUE TITLE
FUTURE FREE Translation Updates December14, 2023

### ISSUE THREAD

**Issue by wocmultimedia** [publishpress/PublishPress-Future#609]
Hi @andergmartins , @stevejburge 
Here's copy of FUTURE FREE Translation Updates. I also updated the translations ES-FR-IT on WP.org.
[Future_FREE_TranslationUpdates_December14_2023.zip](https://github.com/publishpress/PublishPress-Future/files/13673552/Future_FREE_TranslationUpdates_December14_2023.zip)

Thanks,
Angelo

**Comment by andergmartins** [comment]
Thanks @wocmultimedia
