### ISSUE TITLE
Two Typos in SettingsPostTypesModel.php

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#610]
> Here is my error reports, it's always about line 41 / 42 / 43 of SettingsPostTypesModel.php
> 
> Also found a typo-error there: it says 'temrs' instead of 'terms', but changing this did not fix the overall problem of crashing wordpress!

![Screenshot 2023-12-14 at 8 20 28 AM](https://github.com/publishpress/PublishPress-Future/assets/3868028/1e60253a-39d2-4b78-8c7d-cd9b0c4019fc)

**Comment by stevejburge** [comment]
A second typo in line 56 in SettingsPostTypesModel.php:

      'termsName' => $tersmName,

**Comment by andergmartins** [comment]
Thanks, @stevejburge, good catch, and considering both the definition of the variable and the variable call have the same typo it doesn't reflect as a real issue in terms of the code execution. I'm submitting a fix for that.
