### ISSUE TITLE
Add "How to Expire" to Quick Edit

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#62]
> Question: I would love to see the “How to Expire” dropdown available with the Quick Edit. Any chance that could be a future feature add?
https://wordpress.org/support/topic/quick-edit-how-to-expire/

**Comment by contactashish13** [comment]
@stevejburge do you think this is required in bulk edit as well?

**Comment by stevejburge** [comment]
@contactashish13 if possible, yes please

**Comment by contactashish13** [comment]
@stevejburge I believe only this part is required

![image](https://user-images.githubusercontent.com/12953439/129536265-d1428238-dfdc-4887-8aae-78c2192b7733.png)

and not the category dropdown too. Can you please confirm my assumption is correct?

**Comment by stevejburge** [comment]
@contactashish13 yes, please. That's correct, although we don't need the text underneath

**Comment by stevejburge** [comment]
@contactashish13 it's not possible to use the Category selector on Quick Edit or Bulk Edit:

![Screen Shot 2021-08-18 at 9 36 41 AM](https://user-images.githubusercontent.com/3868028/129907868-e7025d59-98af-457e-a4da-482d53b56c55.png)

**Comment by contactashish13** [comment]
@stevejburge I'm not sure what you mean. If I select one of those last 3 options and save, it is saved both in quick edit and bulk edit. I refresh the post listing screen and the option that I selected appears to be saved. Am I missing something?

**Comment by stevejburge** [comment]
@contactashish13 Sorry, I should have explained that better.

After choosing "Category: Add", you need to choose which category to add.

That's how it works on the post editing screen.

**Comment by contactashish13** [comment]
@stevejburge That is what I was asking [here](https://github.com/publishpress/PublishPress-Future/issues/62#issuecomment-899333593 ) when you confirmed that we do not need the category dropdown. I'll implement those too.

**Comment by stevejburge** [comment]
Sorry @contactashish13. Yes, I should have explained that better

**Comment by contactashish13** [comment]
@stevejburge I was able to reproduce the issue here: https://github.com/publishpress/PublishPress-Future/issues/62#issuecomment-906476487 as well. This happened when the settings were not configured (activate plugin but do not save settings).
