### ISSUE TITLE
Hide Metadata dropdown

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#622]
This is probably only useful for 0.1% of users but we're showing it to everyone.

Could we make this a setting under the "Advanced" tab?
![Screenshot 2023-12-15 at 10 24 29 AM](https://github.com/publishpress/PublishPress-Future/assets/3868028/420718d0-38cf-4b62-990a-4d7e1b6212d0)

**Comment by andergmartins** [comment]
@stevejburge I think it needs to be kept as a bulk action so it allows the user to select what posts they want to run that action. But I see your your point, we can add a setting on the advanced tab to  enable or disable this feature (disabled by default)

**Comment by stevejburge** [comment]
Thanks. Maybe it could use a new label? I'm not 100% sure what it does

**Comment by andergmartins** [comment]
@stevejburge Originally, the post-expiration configuration was stored in the post metadata. That allowed other plugins to manipulate that data using the wp metadata API.

But after we implemented the new actions scheduler that information was moved to a custom table + the schedule table. The expiration data was removed from the post metadata.

But some users complained about that change saying they were heavily using the post metadata to integrate with other plugins. So, a solution was implementing that bulk action that allows user to fill the expiration data in the post metadata and after running that bulk action the plugin extract that information and properly schedule the post expiration.

**Comment by stevejburge** [comment]
Thanks @andergmartins. Seems like a good feature to enable under the Advanced settings please

**Comment by andergmartins** [comment]
Thanks. We could display it if the Metadata Scheduling is enabled. Otherwise, hide it, but it would become a Pro feature.

**Comment by stevejburge** [comment]
Good idea. For 90% of people, this will just be confusing
