### ISSUE TITLE
Default date/time offset not working on Classic Editor

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Future#623]
![image](https://github.com/publishpress/PublishPress-Future/assets/83811723/33f944e9-7873-4234-81c9-d46021acdbad)

Even when I set default date/time offset to +1 weeks, on Classic editor it shows 1970

![image](https://github.com/publishpress/PublishPress-Future/assets/83811723/7a8f8528-57de-4575-9d65-c0441a68ad10)

Working fine on Gutenberg

**Comment by andergmartins** [comment]
I can replicate it, but only for new posts.
