### ISSUE TITLE
The plugins is not compatible with PW 5.5. createReduxStore is not a function.

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Future#627]
In WP 5.5 we can't use the future action form. The console shows the error:

```
Uncaught TypeError: (0 , _wp.createReduxStore) is not a function
    at createStore (data.jsx:24:19)
    at _window.inlineEditPost.edit (quick-edit.jsx:70:9)
    at HTMLButtonElement.<anonymous> (inline-edit-post.min.js?ver=5.5.13:2:952)
    at HTMLTableSectionElement.dispatch (load-scripts.php?c=1&load%5Bchunk_0%5D=jquery-core,utils&ver=5.5.13:3:12369)
    at r.handle (load-scripts.php?c=1&load%5Bchunk_0%5D=jquery-core,utils&ver=5.5.13:3:9088)
createStore @ data.jsx:24
_window.inlineEditPost.edit @ quick-edit.jsx:70
(anonymous) @ inline-edit-post.min.js?ver=5.5.13:2
dispatch @ load-scripts.php?c=1&load%5Bchunk_0%5D=jquery-core,utils&ver=5.5.13:3
r.handle @ load-scripts.php?c=1&load%5Bchunk_0%5D=jquery-core,utils&ver=5.5.13:3
```

We need to fix that or bump the min required version

**Comment by stevejburge** [comment]
@andergmartins I'm not sure we need to support back to 5.5

**Comment by andergmartins** [comment]
@stevejburge right, I see the min supported is 6.1. I could make it compatible with 6.0 at least, but that requires having a custom date field for 6.0, without the calendar.

**Comment by stevejburge** [comment]
Honestly, I'm happy leaving support at 6.1. Particularly with the holidays approaching, let's get the beta out as an official release. 

People can update to at least 6.1

**Comment by andergmartins** [comment]
Min WP version set to 6.1 on 71da6422f31f3e4d0f606aead7904c75529f388f
