### ISSUE TITLE
Conflict with dFlip Book plugin

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Future#629]
![image](https://github.com/publishpress/PublishPress-Future/assets/83811723/dffec94c-227d-4524-a99f-fa17f2f36873)

Step to replicate:
1. Install: https://wordpress.org/plugins/3d-flipbook-dflip-lite/
2. Create new book
3. Enable Future action

**Comment by andergmartins** [comment]
Note to self: This is also happening in the Post Type settings page. It has to be with the way we are calling the taxonomy endpoint for custom post types, or custom taxonomies.

**Comment by andergmartins** [comment]
This happens because that plugin do not expose the taxonomy to the rest API:

```
register_taxonomy( 'dflip_category', 'dflip', array(
        'hierarchical'      => true,
        'public'            => true,
        'show_ui'           => true,
        'show_admin_column' => true,
        'show_in_nav_menus' => true,
        'rewrite'           => array( 'slug' => 'dflip_category' ),
    ) );
```

It is missing the `'show_in_rest'      => true` attribute.

**Comment by rizaardiyanto1412** [comment]
![image](https://github.com/publishpress/PublishPress-Future/assets/83811723/4c009f7e-480b-4fb6-86c3-5cf0823d4475)

Now the error happens on Pages

**Comment by andergmartins** [comment]
For pages it is throwing the error:

<img width="811" alt="image" src="https://github.com/publishpress/PublishPress-Future/assets/407131/3d1a2ae5-03f8-4abf-bf09-8fcbb0f0edf8">
