### ISSUE TITLE
Possible issue with taxonomies not being found

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#630]
https://wordpress.org/support/topic/cannot-select-folder-after-3-1-5-ugprade-no-folder-found/

![G6g03xU](https://github.com/publishpress/PublishPress-Future/assets/3868028/5b7c430b-6bfb-4175-965f-2aa2e3d950ee)

**Comment by stevejburge** [comment]
https://wordpress.org/support/topic/product-category-selection-broken/
![GORQqrI8](https://github.com/publishpress/PublishPress-Future/assets/3868028/c9e8c147-c543-4d71-ab98-d5e2c1c0ee4c)

**Comment by stevejburge** [comment]
One more here: https://wordpress.org/support/topic/no-custom-taxonomy-terms-found/

**Comment by rizaardiyanto1412** [comment]
@stevejburge This is related to https://github.com/publishpress/PublishPress-Future/issues/629#issuecomment-1860598314

**Comment by andergmartins** [comment]
I can't replicate this anymore, but I'm waiting for more info from the users that reported it.

**Comment by andergmartins** [comment]
We are not able to replicate this on the most recent beta package. We are closing this one for now and will reopen if any new report is received.
