### ISSUE TITLE
Bug with new WooCommerce HPOS

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#643]
I can confirm this bug:
https://wordpress.org/support/topic/ppf-3-1-6-crashes-site/
![Screenshot 2023-12-28 at 4 47 47 PM](https://github.com/publishpress/PublishPress-Future/assets/3868028/76f8d909-5218-43c2-83ec-8157a1e7a871)

**Comment by dbbrian** [comment]
I can confirm it's also affecting one of my plugins, with a `null` instead of a `WC_Order given`.

**Comment by andergmartins** [comment]
Hey guys, thanks for the details.
I see this is related to #640. There is a new beta package addressing it: https://github.com/publishpress/PublishPress-Future/releases/tag/3.1.7-beta.2
