### ISSUE TITLE
Hide "Auto-enable" settings if not needed

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#644]
Can we hide "Auto-enable"-related settings such as "Action" if they are not needed
![product-settings](https://github.com/publishpress/PublishPress-Future/assets/3868028/d72f87b9-d768-4352-8b87-e855416b5623)

**Comment by andergmartins** [comment]
@stevejburge All those fields are not necessarily related to "auto-enable".

Even when Auto-Enable is disabled, the Taxonomy field is required, so when the user manually selects a taxonomy-related action, it knows what taxonomy is used for showing the terms.

The Action field is also not dependent on that. When the user manually enables future action for a post, the default action is the one selected here.

The same happens on Default Date/Time Offset.
