### ISSUE TITLE
Bug with Custom Post Type

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Future#645]
https://wordpress.org/support/topic/bug-with-custom-post-types-2/

@andergmartins I haven't had any idea on how to replicate this issue. 

I directly create GitHub issue since the report already pinpoint specific line of code 

Please feel free to let me know if I need to dig down on more information on how to replicate this issue.

**Comment by andergmartins** [comment]
Thanks @rizaardiyanto1412 
This is a duplication of https://github.com/publishpress/PublishPress-Future/issues/640
