### ISSUE TITLE
Minified React error #299 from classic-editor.js

### ISSUE THREAD

**Issue by mjot** [publishpress/PublishPress-Future#658]
## Expected Behavior
Wordpress Admin should load without js Errors in Console.

## Current Behavior

If I'm loading the Page Edit Screen to modify a Page I get the following JS error:

```
Uncaught Error: Minified React error #299; visit https://reactjs.org/docs/error-decoder.html?invariant=299 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at e.createRoot (react-dom.min.js?ver=18.2.0:10:127258)
    at classic-editor.jsx:52:9
    at classic-editor.js?ver=3.1.7:1:36297
    at classic-editor.js?ver=3.1.7:1:36301
```

The mentioned classic-editor.js is in wp-content/plugins/post-expirator/assets/js/

## Steps to Reproduce (for bugs)

1. Activate Plugin Version 3.1.7
2. Go to Page Edit screen

## Context

Disabled all other Plugins, problem persists.

## Your Environment

* Version used: Wordpress 6.4.2, post-expirator 3.1.7
* Browser Name and version: Chrome 120.0.6099.234
* Operating System and version (desktop or mobile): Mac OS Sonoma 14.2.1 (23C71)

**Comment by andergmartins** [comment]
@mjot thanks for reporting the error.
I was not able to replicate the issue. Do you have another site to confirm the same bug?

Do you see the metabox PublishPress Future in the right side? If not, please could you check if it is available in the Screen Options? If so, activate it and try refreshing the page.

**Comment by andergmartins** [comment]
Considering we can't replicate this and there is no new feedback we are closing it for now.
