### ISSUE TITLE
Update footer

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#667]
- Remove X
- Documentation https://publishpress.com/knowledge-base/future-introduction/
- Contact https://publishpress.com/publishpress-support/
![Screenshot 2024-01-26 at 10 27 18 AM](https://github.com/publishpress/PublishPress-Future/assets/3868028/fa2ceb66-38ca-4d80-a4ac-9340d0c38008)

**Comment by andergmartins** [comment]
@stevejburge Future has Facebook too. Should I also remove Facebook?

![image](https://github.com/publishpress/PublishPress-Future/assets/407131/f21c5d3e-ff4a-4390-9c53-f6856d3ec965)

**Comment by stevejburge** [comment]
Yeah, let's keep it simple. These social networks are a pain
