### ISSUE TITLE
Default Action Taxonomy Label Issue

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Future#676]
![image](https://github.com/publishpress/PublishPress-Future/assets/83811723/26b7a4b1-4805-4457-a82f-3fdeb76060bf)
![image](https://github.com/publishpress/PublishPress-Future/assets/83811723/4003e16b-a51a-4d18-bfa9-98659a8063c9)

There is labeling issue on default action

**Comment by andergmartins** [comment]
@rizaardiyanto1412 that happens after you change the taxonomy, but didn't save the settings yet, right? After saving, it shows correctly, right?
