### ISSUE TITLE
Add PublishPress Footer

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#68]
![Screen Shot 2021-07-29 at 10 56 10 AM](https://user-images.githubusercontent.com/3868028/127515078-9dafc6bb-183f-4b84-b9b8-62dd0b58e859.png)

**Comment by htmgarcia** [comment]
@stevejburge already added a PR for the footer https://github.com/publishpress/PublishPress-Future/pull/109
