### ISSUE TITLE
Future FREE v3.3.0 Translation Updates ES-FR-IT

### ISSUE THREAD

**Issue by wocmultimedia** [publishpress/PublishPress-Future#685]
Hi @andergmartins , @stevejburge , @htmgarcia ,

Here's copy of the files of Future FREE v3.3.0 Translation Updates ES-FR-IT

[FutureFREE_v3.3.0_TranslationsUpdatesES-FR-IT.zip](https://github.com/publishpress/PublishPress-Future/files/14452801/FutureFREE_v3.3.0_TranslationsUpdatesES-FR-IT.zip)
Please, set into the languages folder.
Thanks,
Angelo

**Comment by andergmartins** [comment]
Thanks @wocmultimedia
