### ISSUE TITLE
Support for imported posts / a default setting for posts created by API

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#69]
> I make posts by filling out a form in Formidable Pro.This will make a post.
> But: the Post Expirator box on de post page doesn’t show the expirator date,
> and there is no expiration date for the post in an extra column on the Posts screen. It says: “Nooit” (Never)
> nor is the checkbox in the Quick Edit / Bulk edit settings activated.
> 
> When I hit the Update button, the date is shown in the expirator box, the post screen shows the expiration date and the checkbox is activated.
> The plugin works perfect…. After I hit that Update Button.

This is closely related to https://github.com/publishpress/PublishPress-Future/issues/38

**Comment by stevejburge** [comment]
> Hi, I would like to set the post expirator to be enabled by default for every post, since I am using Feedzy to automatically create posts and don’t have to the opportunity to set it myself at the time of creation.

**Comment by rizaardiyanto1412** [comment]
Another request: https://wordpress.org/support/topic/cron-event-not-found-5/

**Comment by stevejburge** [comment]
Here's a couple of good examples with the Postie plugin:
https://wordpress.org/support/topic/publishpress-future-post-expiry-time/?view=all
https://wordpress.org/support/topic/no-payload-on-save_post/#post-16255957

I don't think the “Cron Event Not Found” is helpful here. Could we do 2 things:

1. Support imported posts in the Pro version
2. Have a more graceful failure in the Free version

**Comment by stevejburge** [comment]
More:

> Specifically, the cron to unpublish only gets created when a user presses "Update" on a post, but I have posts that are imported nightly from an XML file, including the custom fields necessary to expire the post with your plugin. But since nobody ever presses "update" (since they are imported), the cron to unpublish never gets scheduled.
> 
> I was hoping the paid version of your product has a 'cleanup' cron that runs more often to search out posts that do not have a corresponding cron, and adds the cron back in?

**Comment by andergmartins** [comment]
Another request: https://secure.helpscout.net/conversation/2337011610/209079?folderId=2557461

**Comment by andergmartins** [comment]
This is now partially implemented after we added the bulk action to update the scheduler based on the post metadata.
