### ISSUE TITLE
Bug with Daylight Savings Time

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#71]
https://wordpress.org/support/topic/daylight-savings-issue/

```
I use the [postexpirator] shortcode to display when the post will be deleted. I enabled post expiration and set the parameters to the following:

Year: 2021
Month: November
Day: 15
Hour(CST): 15
Minute: 30

Because I have it set as D, m/d/y \a\t g:i a, the shortcode should result in “Mon, 11/15/21 at 3:30 pm.” Instead, it is showing 4:30 pm.

The site is set to the Chicago time zone and I can only assume this has to do with daylight savings. Is there anyway around this?

Strange. When I set “Show in post footer?” to yes, it generates the correct “Mon, 11/15/21 at 3:30 pm.” Any ideas?
```

**Comment by andergmartins** [comment]
This was fixed on the #134. I you still have issue with a 1h diff on the Gutenberg editor, that is probably related to the Daylight saving time data in PHP, or JS for the the timezone you have set. Here in Brazil I'm on "America/Sao_Paulo", UTC-3h. Daylight saving time is not used every year. This year for example we don't have it. So if the server time is "13:00" and I use "America/Sao_Paulo" in WordPress, it will display the time as "11:00", UTC-2h. But we don't have DST this year, so I'm forced to set WordPress to use the timezone as "UTC -3h" instead. Setting the timezone offset solves the issue.
