### ISSUE TITLE
Different timezone in Post Editing and Quick Edit

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#73]
> The default expiry time for new or edit posts is local CDT – but with Quick Edit it’s UTC.

https://wordpress.org/support/topic/time-difference-between-new-and-quick/#post-14746051

Could potentially be a related issue: https://github.com/publishpress/PublishPress-Future/issues/71

**Comment by Daf57** [comment]
Screenshots added.
screenshot 1 = full edit, time is local.
screenshot 2 = quick edit (same post) time is UTC
screenshot 3  =  WP time settings
Thanks
![postexp1](https://user-images.githubusercontent.com/88691076/128785990-38157e3c-e877-417b-beab-7be9b94796aa.jpg)
![postexp2](https://user-images.githubusercontent.com/88691076/128785991-8aa033be-be2a-4e03-9953-5e43e40d1fdd.jpg)
![postexp3](https://user-images.githubusercontent.com/88691076/128785993-b99af42a-514e-4e2a-9562-86775f3f4eea.jpg)

**Comment by stevejburge** [comment]
thanks @Daf57 

We aim to clean up a bunch of these time issues in version 2.7

**Comment by andergmartins** [comment]
According to my tests, this was fixed on #134
