### ISSUE TITLE
Select multiple node by pressing shift when clicking and selecting in the workflow board.

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#746]
This doesn't seem to be true?
![Screenshot 2024-05-24 at 10 57 03 AM](https://github.com/publishpress/PublishPress-Future/assets/3868028/a8b2e79d-9448-48d3-8851-388b31cd3750)

**Comment by andergmartins** [comment]
@stevejburge it seems to work here. Maybe the description is not accurate?


https://github.com/publishpress/PublishPress-Future/assets/407131/8ea90803-b977-4919-9b08-e362410eb093

**Comment by andergmartins** [comment]
The way it is written seems to point to another feature, select multiple nodes by pressing `CMD` and clicking on the nodes

**Comment by andergmartins** [comment]
@stevejburge maybe we need two tips:

1. Select multiple steps by pressing <kbd>shift</kbd> when clicking and dragging the mouse in the workflow board.
2. Select multiple steps by pressing <kbd>cmd</kbd> and clicking on each step in the workflow.

**Comment by andergmartins** [comment]
Ok, thanks @stevejburge I can't replicate the issue here, so I'm removing that tip for now. Let's leave the other one as the default way to select multiple nodes.
