### ISSUE TITLE
Disable advanced items by default

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#748]
These do make the screen noisy

![Screenshot 2024-05-24 at 10 18 50 AM](https://github.com/publishpress/PublishPress-Future/assets/3868028/5b86d567-8a66-48e5-82d0-cdf3623311a8)

**Comment by andergmartins** [comment]
I moved the node slug to a tooltip when the node is hovered, and to the node card displayed when it is selected (if advanced settings is enabled).

![image](https://github.com/publishpress/PublishPress-Future/assets/407131/8717ada0-30df-4339-bd5a-a6698314b7e3)

![image](https://github.com/publishpress/PublishPress-Future/assets/407131/dce05a0d-a3d7-4f11-bf60-7404c9f44340)

**Comment by andergmartins** [comment]
Added an item to the "more" menu:

![image](https://github.com/publishpress/PublishPress-Future/assets/407131/48627d11-b863-4f95-8928-53d605b4f428)

**Comment by stevejburge** [comment]
Good solution, thanks @andergmartins. I don't think most normal users need to see the slug. That's definitely "Advanced"
