### ISSUE TITLE
Validation for Query Posts

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#751]
The Validation messages are not clear:

This node requires an incoming connection
This node requires an outgoing connection

![Screenshot 2024-05-24 at 11 14 10 AM](https://github.com/publishpress/PublishPress-Future/assets/3868028/eaa1e6d2-57b6-41b2-b82d-0718b9a96ad5)

**Comment by stevejburge** [comment]
Same with Future Action

![Screenshot 2024-05-24 at 12 34 52 PM](https://github.com/publishpress/PublishPress-Future/assets/3868028/5b025ded-53df-4080-9e7f-c08980f80260)

**Comment by andergmartins** [comment]
@stevejburge do these messages sound more clear?

* This step requires a connection from a previous step.
* This step requires a connection to a following step.

**Comment by stevejburge** [comment]
Much better, thanks
