### ISSUE TITLE
Schedule tab

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#759]
- Replace "Recurrence" with "Repeating Action"
- Priority: what do we do with this tab?

![Screenshot 2024-05-24 at 12 28 08 PM](https://github.com/publishpress/PublishPress-Future/assets/3868028/9c73275d-d693-4db6-a89b-b762a453d6d7)

**Comment by stevejburge** [comment]
"On a specific date"
"Relative to a specific date"

![Screenshot 2024-05-24 at 12 31 59 PM](https://github.com/publishpress/PublishPress-Future/assets/3868028/7098e391-6add-448a-89f4-094de06dfdf5)


"Please use only phrases in English."

![Screenshot 2024-05-24 at 12 33 01 PM](https://github.com/publishpress/PublishPress-Future/assets/3868028/de920ec2-1836-4587-af5a-eb9a7679c5dd)

**Comment by andergmartins** [comment]
@stevejburge "Priority" says which scheduled action will run first if many are scheduled for "as soon as possible", or on the same scheduled time.
Maybe we add that as optional if an "Advanced mode is enabled?"

**Comment by stevejburge** [comment]
@andergmartins Yes, hiding it for an Advanced mode would be good
