### ISSUE TITLE
Settings for the schedule tab

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#767]
If you choose "Relative to a specific date", I'm not sure what these settings mean:
![Screenshot 2024-06-05 at 10 46 47 AM](https://github.com/publishpress/PublishPress-Future/assets/3868028/6632cc58-e15f-43ca-b087-29916d504289)

**Comment by andergmartins** [comment]
@stevejburge "Event date" is the date when the event of triggering the workflow happened.

**Comment by stevejburge** [comment]
That sounds good. Maybe we remove the others?
