### ISSUE TITLE
Empty settings

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#768]
I do wonder about this box. What does it mean to be empty? Do this apply to all post types? All status types?

![Screenshot 2024-06-05 at 10 38 14 AM](https://github.com/publishpress/PublishPress-Future/assets/3868028/41b700e3-6d96-43eb-8806-1b0ff3b2b532)

**Comment by andergmartins** [comment]
@stevejburge yes. If empty (no post type specified, or no post id, or no post status) then any post, page, woocommerce orders, etc, on any state will be included.

**Comment by andergmartins** [comment]
But thinking now, maybe that is a little harmful. We probably should require specifying the post type. Then the other fields are optional.

**Comment by stevejburge** [comment]
Yes, for example MetaSlider uses post types. We would not want to
automatically include those.

Maybe we add some default choices such as “Posts”. If for box is empty,
that’s an error.
