### ISSUE TITLE
Update the promo sidebar in the Free version

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#774]
Let's update the promo bar sidebar to include mention of the Workflows feature

**Comment by andergmartins** [comment]
@stevejburge What about this text:

* Design custom workflows with multiple actions
* Schedule actions based on the post's publishing date
* Move posts to custom statuses
* Use other plugins to control Future Actions
* Enjoy fast and professional support

**Comment by stevejburge** [comment]
@andergmartins Sure thing, that works
