### ISSUE TITLE
Show Workflows in the Posts table

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#776]
Should we also show scheduled workflows in the Posts table?
![Screenshot 2024-06-11 at 3 51 17 PM](https://github.com/publishpress/PublishPress-Future/assets/3868028/e15884b3-b6e8-4fd9-a3c2-4f4ab936822a)

**Comment by andergmartins** [comment]
This one is required to fix #792

**Comment by andergmartins** [comment]
Still in progress:

* [ ] Improve scheduling display in the Future Action column;
* [ ] When two workflows are set to schedule tasks when manually selected, only the first schedules a task. It seems like it gets only the first one;
* [ ] Fix the quick-edit panel when the column exists but legacy actions are disabled for the post type. It shows an empty fieldset;
