### ISSUE TITLE
Add Promo screen for Workflows

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#777]
In the Free version of Future, should we add a promo screen like we have for Admin Menus in PublishPress Capabilities?

**Comment by andergmartins** [comment]
@stevejburge the final result

![image](https://github.com/publishpress/PublishPress-Future/assets/407131/b949acd2-e504-4716-8b22-7256591b33c0)

The UI mockup are just a set of images.

**Comment by andergmartins** [comment]
@stevejburge please, could you review the text?
