### ISSUE TITLE
Fatal Error Uncaught ArgumentCountError

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Future#779]
[01-Jun-2024 17:19:27 UTC] PHP Fatal error: Uncaught ArgumentCountError: 8 arguments are required, 4 given in /home/yekrwper/public_html/wp-content/plugins/post-expirator/src/Views/menu-general.php:83
Stack trace: 0 /home/yekrwper/public_html/wp-content/plugins/post-expirator/src/Views/menu-general.php(83): sprintf() 1 /home/yekrwper/public_html/wp-content/plugins/post-expirator/legacy/classes/Display.class.php(429): include(‘/home/yekrwper/…’) 2 /home/yekrwper/public_html/wp-content/plugins/post-expirator/legacy/classes/Display.class.php(330): PostExpirator_Display->render_template() 3 /home/yekrwper/public_html/wp-content/plugins/post-expirator/legacy/classes/Display.class.php(82): PostExpirator_Display->menu_general() 4 /home/yekrwper/public_html/wp-content/plugins/post-expirator/legacy/classes/Display.class.php(108): PostExpirator_Display->load_tab() 5 /home/yekrwper/public_html/wp-includes/class-wp-hook.php(324): PostExpirator_Display->settings_tabs() 6 /home/yekrwper/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() 7 /home/yekrwper/public_html/wp-includes/plugin.php(517): WP_Hook->do_action() 8 /home/yekrwper/public_html/wp-admin/admin.php(259): do_action() 9 {main}

thrown in /home/yekrwper/public_html/wp-content/plugins/post-expirator/src/Views/menu-general.php on line 83

Original thread: https://wordpress.org/support/topic/critical-error-wp-with-your-plugin/

**Comment by andergmartins** [comment]
I just asked for more information from the user who reported it. The error message is obvious, but I can't see the bug in the code. I think he might be using an outdated package.
