### ISSUE TITLE
Stop the Post Expirator box from appearing in non-public post types

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#78]
Here's an example from the PublishPress plugin

![Screen Shot 2021-08-19 at 10 24 58 AM](https://user-images.githubusercontent.com/3868028/130086357-bbf6034b-d9f9-40c0-be90-7d325d75ef36.png)

**Comment by contactashish13** [comment]
@stevejburge I've made is so that by default they will be shown only in posts and pages. Let me know if that's okay.

**Comment by stevejburge** [comment]
@contactashish13 Yes, that's great. Thanks
