### ISSUE TITLE
Possible to show only the workflow checkbox

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#792]
Right now if you disable the normal Future Action box, it disables the workflow checkbox too. Can we manage those separately? Some users may not want the default actions

![Screenshot 2024-06-17 at 4 50 48 PM](https://github.com/publishpress/PublishPress-Future/assets/3868028/6b39d63b-f9ce-4289-88e7-0250970fdbc6)

Enabled together:
![Screenshot 2024-06-17 at 4 52 22 PM](https://github.com/publishpress/PublishPress-Future/assets/3868028/2b71b57f-3512-4f3f-8124-7fc3ae6d55c6)

Disabled together:

![Screenshot 2024-06-17 at 4 52 43 PM](https://github.com/publishpress/PublishPress-Future/assets/3868028/763a00a6-693e-4c79-94e7-6f408145f411)

**Comment by andergmartins** [comment]
Note to self: This happens because when the default box is disabled it also disables the Future Action custom column. With no custom column, the action "quick_edit_custom_box" will not be triggered. 

We need to solve #776 before solving this one.
