### ISSUE TITLE
Notices on Scheduled Actions table

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#811]
Notice: Array to string conversion in /home/rudubanipo2600/web/steady-goat-305466.instawp.xyz/public_html/wp-content/plugins/publishpress-future-pro/lib/vendor/publishpress/publishpress-future/src/Modules/Expirator/Tables/ScheduledActionsTable.php on line 619
![Screenshot 2024-06-21 at 3 01 22 PM](https://github.com/publishpress/PublishPress-Future/assets/3868028/f90f3bee-1097-4663-8be6-f671245b6842)

**Comment by andergmartins** [comment]
Fixed on #810
