### ISSUE TITLE
Add help text for the Priority field

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Future#812]
When "Advanced Mode" is enabled the step Schedule shows a setting field named "Priority".
We probably need some help text.

![image](https://github.com/publishpress/PublishPress-Future/assets/407131/2e3141c0-126a-410e-8ee4-43795183880a)

**Comment by andergmartins** [comment]
@stevejburge, here is a suggestion for the help text:

"Sets the execution priority of the scheduled step. Lower numbers indicate higher priority and are executed first."

![image](https://github.com/publishpress/PublishPress-Future/assets/407131/6faea874-b9cb-4b94-9d9e-e0ac6324edd0)

**Comment by stevejburge** [comment]
@andergmartins Sure, that works
