### ISSUE TITLE
Add an easy way to see the available variables

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Future#819]
We only display the global variables. Until we have a better approach like autocompleting, could we display the variables available to the selected node in the Advanced mode?

**Comment by stevejburge** [comment]
Yes, good point. I think it should be shown for the email step.

I wonder if it's useful for other steps?

**Comment by andergmartins** [comment]
@stevejburge right now, just for the email step. In the future, for the others.
I will display it for any selected post for now if Advanced Mode is enabled. Then we work to improve this on a next release. Even not useful for the other steps, I think it helps to understand the data flow.
