### ISSUE TITLE
Can't click in Category box

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#82]
In my testing, it was impossible to select a category:
<img width="382" alt="Screen Shot 2021-08-23 at 10 51 13 AM" src="https://user-images.githubusercontent.com/3868028/130468558-31ff8c9b-6878-424f-a427-a1af05b5734b.png">

**Comment by contactashish13** [comment]
@stevejburge this is pretty strange. Now even I get this error **without having changed the block source code** and I can't seem to get rid of it. Maybe it is a react/react dom issue. Can Valentin help?

**Comment by stevejburge** [comment]
@htmgarcia can you take a look?

**Comment by htmgarcia** [comment]
@stevejburge I wasn't able to reproduce. Works fine in my end and no errors in console:
![Screen Shot 2021-08-30 at 10 58 45](https://user-images.githubusercontent.com/4999794/131368563-75d1f6e7-3f1f-4914-9657-69ba7e8bf10d.png)

**Comment by stevejburge** [comment]
@htmgarcia Sorry, can you check with the new pre-release version

[post-expirator.v2.5beta3.zip](https://github.com/publishpress/PublishPress-Future/files/7078540/post-expirator.v2.5beta3.zip)

**Comment by htmgarcia** [comment]
@contactashish13 I was able to reproduce the error. It happens in posts that doesn't have the expiration set for categories.
If you use the latest stable version, set expiration for categories, and then update to the [development package](https://github.com/publishpress/PublishPress-Future/files/7078540/post-expirator.v2.5beta3.zip), you can edit the categories. Please note the dev package uses a new folder name, so be careful to not have 2 instances of the plugin running.

**Comment by contactashish13** [comment]
@htmgarcia I'm not sure what you mean by "set expiration for categories".

**Comment by stevejburge** [comment]
Thanks @contactashish13
