### ISSUE TITLE
Future FREE v3.4.2 Translations Updates ES-FR-IT

### ISSUE THREAD

**Issue by wocmultimedia** [publishpress/PublishPress-Future#873]
Hi @andergmartins , @stevejburge 

Here's copy of the files of Future FREE v3.4.2 Translations Updates ES-FR-IT. I also updated the translations on WP.org

[FutureFREE_v3.4.2_TranslationsUpdatesES-FR-IT.zip](https://github.com/user-attachments/files/16255004/FutureFREE_v3.4.2_TranslationsUpdatesES-FR-IT.zip)

Thanks,
Angelo

**Comment by andergmartins** [comment]
Thanks @wocmultimedia
