### ISSUE TITLE
Error after installing Future PRO 3.4.2

### ISSUE THREAD

**Issue by wocmultimedia** [publishpress/PublishPress-Future#874]
Hi @andergmartins , @stevejburge ,

After installing the latest release it appears a warning that the plugin is not installed in the correct path instead of being publishpress-future-pro it is publishpress-future-pro-3.4.2  

Please, check it

**Comment by andergmartins** [comment]
Thanks @wocmultimedia. Did you install it manually or using Wordpress to update it?

**Comment by wocmultimedia** [comment]
I downloaded the source zip file from here and then installed using the WP. But if you open the zip file you see that the folder is named "publishpress-future-pro-3.4.2" and not "publishpress-future-pro"

**Comment by andergmartins** [comment]
Thanks. To work properly the plugin requires to be installed using the .zip package, built with the correct folder name. 
Using the source code you have a plan repo code inside the zip, without a few adjustments the build script does when packing it.

Please, could you try uninstalling it and installing using one of the packages you can download from the assets sections here? https://github.com/publishpress/PublishPress-Future-Pro/releases

**Comment by wocmultimedia** [comment]
Thanks, before the install zip file wasn't available. You just set it now. I will try later when I come back to office.

18 lug 2024 10:53:26 Anderson Grüdtner Martins ***@***.***>:

**Comment by wocmultimedia** [comment]
I downloaded the available release and it works fine. Thanks

**Comment by andergmartins** [comment]
Cool, thanks
