### ISSUE TITLE
Compatibility with Event Espresso

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Future#889]
Event Espresso plugin: https://wordpress.org/plugins/event-espresso-decaf/

The issue:
![image](https://github.com/user-attachments/assets/0a7d0e7c-5613-44b9-90a3-beec4d619048)

**Comment by FlourishDesignStudio** [comment]
I have the same issue using the Pro version of the plugin! I'm following this thread and hope to learn from it!

**Comment by FlourishDesignStudio** [comment]
Thank you so much for the fix! I updated this week and it now works again! :)
