### ISSUE TITLE
Future FREE_v3.4.3 Translations Updates ES-FR-IT

### ISSUE THREAD

**Issue by wocmultimedia** [publishpress/PublishPress-Future#892]
Hi @andergmartins , @stevejburge 

Here's copy of Future FREE_v3.4.3 Translations Updates ES-FR-IT. I also updated translations on WP.org
[NewTranslationUpdates-FutureFREE-3.4.2.zip](https://github.com/user-attachments/files/16514620/NewTranslationUpdates-FutureFREE-3.4.2.zip)

**Comment by andergmartins** [comment]
Thanks @wocmultimedia
