### ISSUE TITLE
Move the Workflow Editor module to the Free plugin with basic steps

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Future#893]
The Workflow Editor module should be moved to the Free plugin, with basic steps only, keeping  all the Pro steps, but as an informative way to show free users what they can do in the Pro version.

**Comment by stevejburge** [comment]
@andergmartins How about making these 4 into Pro-only items in the first version?

![Screenshot 2024-08-08 at 11 04 17 AM](https://github.com/user-attachments/assets/2e99742f-b966-4ed3-a90a-7f1ba741988d)
![Screenshot 2024-08-08 at 11 03 52 AM](https://github.com/user-attachments/assets/e3ed6866-4638-4e08-8e79-44262702c5bf)

**Comment by andergmartins** [comment]
@stevejburge the only problem I see the Schedule action. Without releasing it in the Free plugin, users won't be able to create useful workflows because the action would happen right the trigger is fired. For example, if a post is saved, it would instantaneously be deleted/stick, etc... The schedule action is what simulates the calendar option we have in the Future Action box right now

**Comment by andergmartins** [comment]
@stevejburge Regarding the Free plugin, maybe we could improve the curiosity about the Pro only steps if we remove them, but keep a placeholder with its description, possible settings, but disabled for running? We can show an small tag `pro` over those icons, for example.

**Comment by stevejburge** [comment]
Yes, please. That's the perfect approach

**Comment by andergmartins** [comment]
Fixed on effa492db6299eed2f2a38d2533f769ce41254e6 and 028efae4a2d567e544c11c187f35c38599418f9b
