### ISSUE TITLE
Appearance Widgets screen shows PHP Notice: 

### ISSUE THREAD

**Issue by contactashish13** [publishpress/PublishPress-Future#92]
## Steps to Reproduce (for bugs)
- Go to Appearance -> Widgets
- The following notice will be thrown
```PHP Notice:  Trying to get property 'post_type' of non-object in ...wp-content\plugins\PublishPress-Future\classes\Facade.class.php on line 327```

WordPress 5.8
PHP 7.2

**Comment by contactashish13** [comment]
@stevejburge just ran into this bug while testing something else on blocks. I believe this is related to changes in #10 so I believe this may need to part of 2.5. Can you please move it to the correct milestone?

**Comment by stevejburge** [comment]
Good catch thanks @contactashish13
