### ISSUE TITLE
Allow admins to customize the email recipients

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#939]
We had a request in Portland to allow admins to customize the email recipients. For example this could be based on a custom field:
![Screenshot 2024-09-23 at 1 12 21 PM](https://github.com/user-attachments/assets/27220e7a-5af6-4aeb-b767-f832f2bd3bfc)

**Comment by andergmartins** [comment]
We can also add more space to the custom email addresses and subject fields
