### ISSUE TITLE
Do we need this warning?

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#952]
I'm not sure this warning applies to some quite normal settings. Should we just move this warning and the 2 Workflow settings to the bottom of the screen? Or should these normal settings get a new tab?

![Screenshot 2024-10-01 at 11 03 55 AM](https://github.com/user-attachments/assets/9cfe662d-2707-45c2-8165-2e059bfb34b9)

**Comment by andergmartins** [comment]
@stevejburge I think we can remove the warning 👍🏻 

Maybe "Future Action Column Style", and "Time format in the date picker" could be moved to the "Display" tab?

### Mockup

![image](https://github.com/user-attachments/assets/6019ddfb-f1d4-4e58-9a35-7bf5e8c94a6c)

**Comment by stevejburge** [comment]
Yes, please. Maybe we can also move the roles option to the "General" tab
