### ISSUE TITLE
Are action workflows missing the normal box design in Quick Edit?

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#954]
Compare a normal Action to a Workflow 

![Screenshot 2024-10-01 at 11 11 32 AM](https://github.com/user-attachments/assets/55750969-d76c-44dc-9858-811df21eddaa)

**Comment by andergmartins** [comment]
This is the fixed version:

![image](https://github.com/user-attachments/assets/75d10cfb-6bb3-477a-b979-6481591f1780)

**Comment by stevejburge** [comment]
Thanks, should we remove the "Action Workflows" title to match the other box?
