### ISSUE TITLE
Update email text for demo emails

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#972]
The email text doesn't always match what's happening in the workflow
![Screenshot 2024-10-17 at 1 34 21 PM](https://github.com/user-attachments/assets/493bd11b-3f39-4293-93fb-bd58d073084f)

**Comment by andergmartins** [comment]
@stevejburge please, could you clarify this one a little more or an example of how to replicate it?

**Comment by stevejburge** [comment]
Thanks @andergmartins. I guess the key problem is probably that this syntax is unclear. We don't offer an explanation of what these mean. This is the solution: https://github.com/publishpress/PublishPress-Future/issues/976

**Comment by andergmartins** [comment]
Thanks, Steve. I will close this one in favor of that other ticket.
