### ISSUE TITLE
Can "Query Posts" be more like "Conditional Split"

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#973]
Can we borrow this code and use it for "Query posts"?

![Screenshot 2024-10-17 at 1 38 39 PM](https://github.com/user-attachments/assets/61cf45f9-6d60-4e25-92ef-525a4d48ffc3)

**Comment by andergmartins** [comment]
@stevejburge I think so, but considering the same result can be achieved using a Conditional step right after the trigger to check the same conditions, do we need to duplicate that in the trigger? It is also a Pro feature.

**Comment by stevejburge** [comment]
OK, thanks. Let's leave it then

**Comment by andergmartins** [comment]
Note to self: reopening this can help to fix #1131
