### ISSUE TITLE
Which boxes are required?

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#974]
Should we be clear about which boxes are required for steps? In this case, only "Post Type" is required?
![Screenshot 2024-10-17 at 1 47 02 PM](https://github.com/user-attachments/assets/c9012384-1f60-4a4b-a104-79250e85de87)

**Comment by andergmartins** [comment]
@stevejburge Is the `*` an option for that? Although we already have an error flag for that when it is empty:

![image](https://github.com/user-attachments/assets/74ccf08d-42d0-4c01-a75c-b3350970070f)

**Comment by stevejburge** [comment]
Yes, please. Just a * would be great
