### ISSUE TITLE
Can we show the variables that people can use for email?

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#976]
If we can't show the variables, could we show a message on how to enable them?
![Screenshot 2024-10-18 at 4 04 27 PM](https://github.com/user-attachments/assets/bf2bde7e-8ada-4970-98b3-7b1da90afcc7)

**Comment by andergmartins** [comment]
## WS Form

![image](https://github.com/user-attachments/assets/178e8864-8f4f-4333-99e4-9f113dc643aa)

![image](https://github.com/user-attachments/assets/649a7af6-a48f-43f8-95d4-575f7d86b7c6)

![image](https://github.com/user-attachments/assets/6b21c049-c0ca-4628-9137-471d3b924f68)

## Ninja forms

![image](https://github.com/user-attachments/assets/fcd44783-114c-482c-8585-6e5f770b67f8)

![image](https://github.com/user-attachments/assets/9f83ef12-38d2-4f14-955a-9353525318cd)
