### ISSUE TITLE
A couple of Pro features are not shown in the Free version

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#996]
Can we add these to the Free version, marked as "Pro"
![Screenshot 2024-10-22 at 2 43 09 PM](https://github.com/user-attachments/assets/360ecda7-bba4-4886-b4e8-82d7deb68142)
![Screenshot 2024-10-22 at 2 43 02 PM](https://github.com/user-attachments/assets/9a8a6243-957e-43bc-91c8-b188763a2ce8)

**Comment by andergmartins** [comment]
@stevejburge weird, I see those in the free version...

![image](https://github.com/user-attachments/assets/9f0152f0-fce9-42d5-8b2e-6787ce2eb799)

![image](https://github.com/user-attachments/assets/16bcef5a-ae0c-44f1-99d2-a386e507bb6e)

![image](https://github.com/user-attachments/assets/19b9eed3-1e16-4b8a-954f-8024bdb20583)

![image](https://github.com/user-attachments/assets/eab76b57-8040-4d22-9483-bdedc363dd20)

**Comment by stevejburge** [comment]
Sorry, you're right. I'm an idiot.

**Comment by andergmartins** [comment]
😄 np @stevejburge 

Any workflow step has 3 layers to exist there. For the Pro steps, we have:

* UI for the editor (JS) - In the free plugin
* Definition code (PHP) - In the free plugin with Pro flag so it can be found by the engine and editor
* Implementation code (PHP) - A dummy with empty logic in the Free plugin, then the real logic implemented in the Pro, overriding the dummy.

That makes it simpler to guarantee all steps are always listed in the free plugin.
